
' ++++++++++++++++++++++++++++++++++++++++++++++++++
' This code is generated by a tool and is provided "as is", without warranty of any kind,
' express or implied, including but not limited to the warranties of merchantability,
' fitness for a particular purpose and non-infringement.
' In no event shall the authors or copyright holders be liable for any claim, damages or
' other liability, whether in an action of contract, tort or otherwise, arising from,
' out of or in connection with the software or the use or other dealings in the software.
' ++++++++++++++++++++++++++++++++++++++++++++++++++
' 

Namespace MySQLTest

Public Class frmMain

    Private Sub frmbuchvorgangToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles frmbuchvorgangToolStripMenuItem.Click
      Dim f As frmbuchvorgang = New frmbuchvorgang()
      f.Show()
    End Sub

    Private Sub frmgrartikelToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles frmgrartikelToolStripMenuItem.Click
      Dim f As frmgrartikel = New frmgrartikel()
      f.Show()
    End Sub

End Class

End Namespace
