ALTER TABLE `intrasell_daten_2`.`buchAngebot` 
 MODIFY COLUMN `Summe` DECIMAL(8,2),
 MODIFY COLUMN `SummeMWST` DECIMAL(8,2),
 MODIFY COLUMN `SummeBrutto` DECIMAL(8,2);


ALTER TABLE `intrasell_daten_2`.`buchAngebot-artikel` 
 MODIFY COLUMN `PreisATS` DECIMAL(8,4) NOT NULL DEFAULT 0,
 MODIFY COLUMN `PreisEuro` DECIMAL(8,4),
 MODIFY COLUMN `Stk` DECIMAL(8,4) NOT NULL DEFAULT 0,
 MODIFY COLUMN `PreisATS_Brutto` DECIMAL(8,4),
 MODIFY COLUMN `EKPreis` DECIMAL(8,4);


ALTER TABLE `intrasell_daten_2`.`buchAuftrag` 
 MODIFY COLUMN `Summe` DECIMAL(8,2),
 MODIFY COLUMN `SummeMWST` DECIMAL(8,2),
 MODIFY COLUMN `SummeBrutto` DECIMAL(8,2);


ALTER TABLE `intrasell_daten_2`.`buchAuftrag-artikel` 
 MODIFY COLUMN `PreisATS` DECIMAL(8,4) NOT NULL DEFAULT 0,
 MODIFY COLUMN `PreisEuro` DECIMAL(8,4),
 MODIFY COLUMN `Stk` DECIMAL(8,4) NOT NULL DEFAULT 0,
 MODIFY COLUMN `PreisATS_Brutto` DECIMAL(8,4),
 MODIFY COLUMN `EKPreis` DECIMAL(8,4);

ALTER TABLE `intrasell_daten_2`.`buchrechnung` 
 MODIFY COLUMN `Summe` DECIMAL(8,2),
 MODIFY COLUMN `SummeMWST` DECIMAL(8,2),
 MODIFY COLUMN `SummeBrutto` DECIMAL(8,2);


ALTER TABLE `intrasell_daten_2`.`buchrech-artikel` 
 MODIFY COLUMN `PreisATS` DECIMAL(8,4) NOT NULL DEFAULT 0,
 MODIFY COLUMN `PreisEuro` DECIMAL(8,4),
 MODIFY COLUMN `Stk` DECIMAL(8,4) NOT NULL DEFAULT 0,
 MODIFY COLUMN `PreisATS_Brutto` DECIMAL(8,4),
 MODIFY COLUMN `EKPreis` DECIMAL(8,4);


ALTER TABLE `intrasell_daten_2`.`buchLieferschein` 
 MODIFY COLUMN `Summe` DECIMAL(8,2),
 MODIFY COLUMN `SummeMWST` DECIMAL(8,2),
 MODIFY COLUMN `SummeBrutto` DECIMAL(8,2);


ALTER TABLE `intrasell_daten_2`.`buchLieferschein-artikel` 
 MODIFY COLUMN `PreisATS` DECIMAL(8,4) NOT NULL DEFAULT 0,
 MODIFY COLUMN `PreisEuro` DECIMAL(8,4),
 MODIFY COLUMN `Stk` DECIMAL(8,4) NOT NULL DEFAULT 0,
 MODIFY COLUMN `PreisATS_Brutto` DECIMAL(8,4),
 MODIFY COLUMN `EKPreis` DECIMAL(8,4);


ALTER TABLE `intrasell_daten_2`.`buchRetourwaren` 
 MODIFY COLUMN `Summe` DECIMAL(8,2),
 MODIFY COLUMN `SummeMWST` DECIMAL(8,2),
 MODIFY COLUMN `SummeBrutto` DECIMAL(8,2);


ALTER TABLE `intrasell_daten_2`.`buchRetourwaren-artikel` 
 MODIFY COLUMN `PreisATS` DECIMAL(8,4) NOT NULL DEFAULT 0,
 MODIFY COLUMN `PreisEuro` DECIMAL(8,4),
 MODIFY COLUMN `Stk` DECIMAL(8,4) NOT NULL DEFAULT 0,
 MODIFY COLUMN `PreisATS_Brutto` DECIMAL(8,4),
 MODIFY COLUMN `EKPreis` DECIMAL(8,4);



ALTER TABLE `intrasell_daten_2`.`buchkassabuch` MODIFY COLUMN `BetragAusgang` DECIMAL(19,4) DEFAULT 0,
 MODIFY COLUMN `BetragEingang` DECIMAL(8,2) DEFAULT 0;