<%@ LANGUAGE = VBScript.Encode%>
<%'@ LANGUAGE = VBScript.Encode  TRANSACTION = Required %>
<%'OPTION explicit%>
<!--#include file="login.asp"-->
<!--#include virtual="/intrasoft/connopen.asp"-->
<!--#include virtual="/intrasoft/functions.asp"-->
<!--#include virtual="/intrasoft/functionsDictionary.asp"-->
<!--#include virtual="/intrasoft/functionsGUI.asp"-->
<!--#include virtual="/intrasoft/functionsCache.asp"-->
<!--#include virtual="/cgi/functionsIntraSellDLL.asp"-->
<!--#include virtual="/cgi/functionsIntraSell.asp"-->
<!--#include virtual="/cgi/functionsPrices.asp"-->
<!--#include virtual="/cgi/functionsOrderInvoice.asp"-->
<!--#include virtual="/cgi/functionsOrderInvoiceDisplay.asp"-->
