'------------------------------------------------------------------------------
'  <auto-generated>
'      This code was generated by coded UI test builder.
'      Version: 10.0.0.0
'
'      Changes to this file may cause incorrect behavior and will be lost if
'      the code is regenerated.
'  </auto-generated>
' ------------------------------------------------------------------------------

Imports System
Imports System.CodeDom.Compiler
Imports System.Collections.Generic
Imports System.Drawing
Imports System.Text.RegularExpressions
Imports System.Windows.Input
Imports Microsoft.VisualStudio.TestTools.UITest.Extension
Imports Microsoft.VisualStudio.TestTools.UITesting
Imports Microsoft.VisualStudio.TestTools.UITesting.WinControls
Imports Microsoft.VisualStudio.TestTools.UnitTesting
Imports Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard
Imports Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse
Imports MouseButtons = System.Windows.Forms.MouseButtons

Namespace IntraSell_Net_UnitTests
    
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Partial Public Class UIMap
        
        '''<summary>
        '''RecordedMethod1
        '''</summary>
        Public Sub RecordedMethod1()
            Dim uIListeMenuItem As WinMenuItem = Me.UIIntraSellNet01AlphabWindow.UIMenuStrip1MenuBar.UIStammdatenMenuItem.UIListeMenuItem
            Dim uISchließenMenuItem As WinMenuItem = Me.UIIntraSellNet01AlphabWindow.UIMenuStrip1MenuBar.UISchließenMenuItem
            Dim uISchließenButton As WinButton = Me.UIIntraSellNet01AlphabWindow.UIIntraSellNet01AlphabTitleBar.UISchließenButton

            'Click 'Stammdaten' -> 'Liste' menu item
            Mouse.Click(uIListeMenuItem, New Point(19, 9))

            'Click 'Schließen' menu item
            Mouse.Click(uISchließenMenuItem, New Point(9, 13))

            'Click 'Schließen' button
            Mouse.Click(uISchließenButton, New Point(25, 9))
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIIntraSellNet01AlphabWindow() As UIIntraSellNet01AlphabWindow
            Get
                If (Me.mUIIntraSellNet01AlphabWindow Is Nothing) Then
                    Me.mUIIntraSellNet01AlphabWindow = New UIIntraSellNet01AlphabWindow()
                End If
                Return Me.mUIIntraSellNet01AlphabWindow
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIIntraSellNet01AlphabWindow As UIIntraSellNet01AlphabWindow
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class UIIntraSellNet01AlphabWindow
        Inherits WinWindow
        
        Public Sub New()
            MyBase.New
            Me.SearchProperties(WinWindow.PropertyNames.Name) = "IntraSell.Net 0.1 Alpha by Grigor Tonkov"
            Me.SearchProperties.Add(New PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains))
            Me.WindowTitles.Add("IntraSell.Net 0.1 Alpha by Grigor Tonkov")
            Me.WindowTitles.Add("IntraSell.Net 0.1 Alpha by Grigor Tonkov - [KundenListe]")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIMenuStrip1MenuBar() As UIMenuStrip1MenuBar
            Get
                If (Me.mUIMenuStrip1MenuBar Is Nothing) Then
                    Me.mUIMenuStrip1MenuBar = New UIMenuStrip1MenuBar(Me)
                End If
                Return Me.mUIMenuStrip1MenuBar
            End Get
        End Property
        
        Public ReadOnly Property UIIntraSellNet01AlphabTitleBar() As UIIntraSellNet01AlphabTitleBar
            Get
                If (Me.mUIIntraSellNet01AlphabTitleBar Is Nothing) Then
                    Me.mUIIntraSellNet01AlphabTitleBar = New UIIntraSellNet01AlphabTitleBar(Me)
                End If
                Return Me.mUIIntraSellNet01AlphabTitleBar
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIMenuStrip1MenuBar As UIMenuStrip1MenuBar
        
        Private mUIIntraSellNet01AlphabTitleBar As UIIntraSellNet01AlphabTitleBar
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class UIMenuStrip1MenuBar
        Inherits WinMenuBar
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinMenu.PropertyNames.Name) = "MenuStrip1"
            Me.WindowTitles.Add("IntraSell.Net 0.1 Alpha by Grigor Tonkov")
            Me.WindowTitles.Add("IntraSell.Net 0.1 Alpha by Grigor Tonkov - [KundenListe]")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIStammdatenMenuItem() As UIStammdatenMenuItem
            Get
                If (Me.mUIStammdatenMenuItem Is Nothing) Then
                    Me.mUIStammdatenMenuItem = New UIStammdatenMenuItem(Me)
                End If
                Return Me.mUIStammdatenMenuItem
            End Get
        End Property
        
        Public ReadOnly Property UISchließenMenuItem() As WinMenuItem
            Get
                If (Me.mUISchließenMenuItem Is Nothing) Then
                    Me.mUISchließenMenuItem = New WinMenuItem(Me)
                    Me.mUISchließenMenuItem.SearchProperties(WinMenuItem.PropertyNames.Name) = "Schließen"
                    Me.mUISchließenMenuItem.WindowTitles.Add("IntraSell.Net 0.1 Alpha by Grigor Tonkov - [KundenListe]")
                End If
                Return Me.mUISchließenMenuItem
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIStammdatenMenuItem As UIStammdatenMenuItem
        
        Private mUISchließenMenuItem As WinMenuItem
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class UIStammdatenMenuItem
        Inherits WinMenuItem
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinMenuItem.PropertyNames.Name) = "Stammdaten"
            Me.WindowTitles.Add("IntraSell.Net 0.1 Alpha by Grigor Tonkov")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIListeMenuItem() As WinMenuItem
            Get
                If (Me.mUIListeMenuItem Is Nothing) Then
                    Me.mUIListeMenuItem = New WinMenuItem(Me)
                    Me.mUIListeMenuItem.SearchProperties(WinMenuItem.PropertyNames.Name) = "Liste"
                    Me.mUIListeMenuItem.SearchConfigurations.Add(SearchConfiguration.ExpandWhileSearching)
                    Me.mUIListeMenuItem.WindowTitles.Add("IntraSell.Net 0.1 Alpha by Grigor Tonkov")
                End If
                Return Me.mUIListeMenuItem
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIListeMenuItem As WinMenuItem
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class UIIntraSellNet01AlphabTitleBar
        Inherits WinTitleBar
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.WindowTitles.Add("IntraSell.Net 0.1 Alpha by Grigor Tonkov")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UISchließenButton() As WinButton
            Get
                If (Me.mUISchließenButton Is Nothing) Then
                    Me.mUISchließenButton = New WinButton(Me)
                    Me.mUISchließenButton.SearchProperties(WinButton.PropertyNames.Name) = "Schließen"
                    Me.mUISchließenButton.WindowTitles.Add("IntraSell.Net 0.1 Alpha by Grigor Tonkov")
                End If
                Return Me.mUISchließenButton
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUISchließenButton As WinButton
        #End Region
    End Class
End Namespace
