
<div align="center">
	<table border="0" cellpadding="0" cellspacing="0" width="100%">
		<tr>
			<td><a href="aspedit.asp" border=0><img src="images/aspedit.gif" width="468" height="60" border="0"></a></td>
			<td valign="bottom">
				<div align="right">
					<b>aspEdit v1.3.0</b><br>
					<font size="-2">Problems, Bugs or Tips to <a href="mailto:saxsucks@hotmail.com">SAXsucks@hotmail.com</a><br>
						Visit <a href="http://saxsucks.go.cc" target="_blank">http://SAXsucks.go.cc</a></font></div>
			</td>
		</tr>
	</table>
	<hr>
</div>
