
ALTER TABLE `intrasell_daten_2`.`ofadressen-seriendruck` MODIFY COLUMN `Land` VARCHAR(25) DEFAULT NULL,
 MODIFY COLUMN `Branche` VARCHAR(50) DEFAULT NULL,
 MODIFY COLUMN `PLZ` VARCHAR(50) DEFAULT NULL,
 MODIFY COLUMN `Export` VARCHAR(50) DEFAULT NULL,
 MODIFY COLUMN `MAAusen` VARCHAR(50) DEFAULT NULL,
 MODIFY COLUMN `MAInnen` VARCHAR(50) DEFAULT NULL,
 MODIFY COLUMN `Abbuchung` VARCHAR(50) DEFAULT NULL,
 MODIFY COLUMN `hasMenu` VARCHAR(50) DEFAULT NULL;


    
  
  
  
  
 
 
 