GRANT REPLICATION SLAVE, REPLICATION CLIENT
    ON *.*
    TO 'replication'@'*'
    IDENTIFIED BY 'efox2004';


-- ARFAIAN_SERVER_2

CHANGE MASTER TO
  MASTER_HOST='80.120.26.138',
  MASTER_USER='replication',
  MASTER_PASSWORD='efox2004',
  MASTER_PORT=3306,
  MASTER_LOG_FILE='master2-bin.00016',
  MASTER_LOG_POS=7968,
  MASTER_CONNECT_RETRY=10;



-- ARFAIAN.COM

CHANGE MASTER TO
  MASTER_HOST='www.arfaian.com',
  MASTER_USER='root',
  MASTER_PASSWORD='a1060',
  MASTER_PORT=3306,
  MASTER_LOG_FILE='mysql-bin.000001',
  MASTER_LOG_POS=106,
  MASTER_CONNECT_RETRY=10;