<%@ LANGUAGE = VBScript.Encode%>
<%'@ LANGUAGE = VBScript.Encode  TRANSACTION = Required %>
<%'OPTION explicit%>
<!--#include file="../client/intrasoft/connOpen.asp"-->
<!--#include file="login.asp"-->
<!--#include file="../client/intrasoft/functions.asp"-->
<!--#include file="../client/intrasoft/functionsDictionary.asp"-->
<!--#include file="../client/intrasoft/functionsGUI.asp"-->
<!--#include file="../client/intrasoft/functionsIntraSell.asp"-->
<!--#include file="../client/functionsMerchants.asp"-->