' ++++++++++++++++++++++++++++++++++++++++++++++++++
' This code is generated by a tool and is provided "as is", without warranty of any kind,
' express or implied, including but not limited to the warranties of merchantability,
' fitness for a particular purpose and non-infringement.
' In no event shall the authors or copyright holders be liable for any claim, damages or
' other liability, whether in an action of contract, tort or otherwise, arising from,
' out of or in connection with the software or the use or other dealings in the software.
' ++++++++++++++++++++++++++++++++++++++++++++++++++
' 

Imports System.ComponentModel
Imports MySql.Data.MySqlClient

Namespace MySQLTest
	
	Public Class frmgrartikel
		
		Private ad As MySqlDataAdapter
		
		Private Sub frmgrartikel_Load(sender As System.Object, e As System.EventArgs) Handles MyBase.Load
			Dim strConn As String = "server=localhost;user id=root;password=a1060;persistsecurityinfo=True;database=intrasell_daten_2;"
			ad = New MySqlDataAdapter("select * from `grartikel`", strConn)
			Dim builder As MySqlCommandBuilder = New MySqlCommandBuilder(ad)
			ad.Fill(Me.newDataSet.grartikel)
			ad.DeleteCommand = builder.GetDeleteCommand()
			ad.UpdateCommand = builder.GetUpdateCommand()
			ad.InsertCommand = builder.GetInsertCommand()
			Dim ad3 As MySqlDataAdapter
		End Sub
		
		Private Sub ToolStripButton1_Click(sender As System.Object, e As System.EventArgs) Handles ToolStripButton1.Click
			If Not Me.Validate() Then
				Return
			End If
			If TypeOf( CType(grartikelBindingSource.Current, DataRowView )( "LagerArtikel" ) ) Is DBNull Then 
				CType(grartikelBindingSource.Current, DataRowView )("LagerArtikel") = LagerArtikelCheckBox.Checked
			End If
			If TypeOf( CType(grartikelBindingSource.Current, DataRowView )( "Seriennummer" ) ) Is DBNull Then 
				CType(grartikelBindingSource.Current, DataRowView )("Seriennummer") = SeriennummerCheckBox.Checked
			End If
			If TypeOf( CType(grartikelBindingSource.Current, DataRowView )( "SetArtikel" ) ) Is DBNull Then 
				CType(grartikelBindingSource.Current, DataRowView )("SetArtikel") = SetArtikelCheckBox.Checked
			End If
			If TypeOf( CType(grartikelBindingSource.Current, DataRowView )( "ProduktAktiv" ) ) Is DBNull Then 
				CType(grartikelBindingSource.Current, DataRowView )("ProduktAktiv") = ProduktAktivCheckBox.Checked
			End If
			If TypeOf( CType(grartikelBindingSource.Current, DataRowView )( "AngelegtAn" ) ) Is DBNull Then 
				CType(grartikelBindingSource.Current, DataRowView )("AngelegtAn") = AngelegtAn_dateTimePicker.Value
			End If
			If TypeOf( CType(grartikelBindingSource.Current, DataRowView )( "AngelegtAm" ) ) Is DBNull Then 
				CType(grartikelBindingSource.Current, DataRowView )("AngelegtAm") = AngelegtAm_dateTimePicker.Value
			End If
			If TypeOf( CType(grartikelBindingSource.Current, DataRowView )( "NichtBestellbar" ) ) Is DBNull Then 
				CType(grartikelBindingSource.Current, DataRowView )("NichtBestellbar") = NichtBestellbarCheckBox.Checked
			End If
			grartikelBindingSource.EndEdit()
			ad.Update(Me.newDataSet.grartikel)
		End Sub
		
		Private Sub frmgrartikel_FormClosing(sender As System.Object, e As System.Windows.Forms.FormClosingEventArgs) Handles MyBase.FormClosing
			e.Cancel = False
		End Sub
		
		Private Sub ArtNrTextBox_Validating(sender As Object, e As CancelEventArgs)
			
			e.Cancel = False
			If String.IsNullOrEmpty( ArtNrTextBox.Text ) Then 
				e.Cancel = True
				errorProvider1.SetError( ArtNrTextBox, "The field ArtNr is required" ) 
			End If
			Dim v As Integer
			Dim s As string = ArtNrTextBox.Text
			If Not Integer.TryParse( s, v ) Then
				e.Cancel = True
				errorProvider1.SetError( ArtNrTextBox, "The field ArtNr must be Integer." )
			End If
			If Not e.Cancel Then
				errorProvider1.SetError( ArtNrTextBox, "" )
			End If
		End Sub
		
		Private Sub EANTextBox_Validating(sender As Object, e As CancelEventArgs)
			
			e.Cancel = False
			If String.IsNullOrEmpty( EANTextBox.Text ) Then 
				e.Cancel = True
				errorProvider1.SetError( EANTextBox, "The field EAN is required" ) 
			End If
			If Not e.Cancel Then
				errorProvider1.SetError( EANTextBox, "" )
			End If
		End Sub
		
		Private Sub BarcodeTextBox_Validating(sender As Object, e As CancelEventArgs)
			
			e.Cancel = False
			If String.IsNullOrEmpty( BarcodeTextBox.Text ) Then 
				e.Cancel = True
				errorProvider1.SetError( BarcodeTextBox, "The field Barcode is required" ) 
			End If
			If Not e.Cancel Then
				errorProvider1.SetError( BarcodeTextBox, "" )
			End If
		End Sub
		
		Private Sub BezeichnungTextBox_Validating(sender As Object, e As CancelEventArgs)
			
			e.Cancel = False
			If String.IsNullOrEmpty( BezeichnungTextBox.Text ) Then 
				e.Cancel = True
				errorProvider1.SetError( BezeichnungTextBox, "The field Bezeichnung is required" ) 
			End If
			If Not e.Cancel Then
				errorProvider1.SetError( BezeichnungTextBox, "" )
			End If
		End Sub
		
		Private Sub Bezeichnung1TextBox_Validating(sender As Object, e As CancelEventArgs)
			
			e.Cancel = False
			If String.IsNullOrEmpty( Bezeichnung1TextBox.Text ) Then 
				e.Cancel = True
				errorProvider1.SetError( Bezeichnung1TextBox, "The field Bezeichnung1 is required" ) 
			End If
			If Not e.Cancel Then
				errorProvider1.SetError( Bezeichnung1TextBox, "" )
			End If
		End Sub
		
		Private Sub BeschreibungTextBox_Validating(sender As Object, e As CancelEventArgs)
			
			e.Cancel = False
			If String.IsNullOrEmpty( BeschreibungTextBox.Text ) Then 
				e.Cancel = True
				errorProvider1.SetError( BeschreibungTextBox, "The field Beschreibung is required" ) 
			End If
			If Not e.Cancel Then
				errorProvider1.SetError( BeschreibungTextBox, "" )
			End If
		End Sub
		
		Private Sub EinheitTextBox_Validating(sender As Object, e As CancelEventArgs)
			
			e.Cancel = False
			If String.IsNullOrEmpty( EinheitTextBox.Text ) Then 
				e.Cancel = True
				errorProvider1.SetError( EinheitTextBox, "The field Einheit is required" ) 
			End If
			If Not e.Cancel Then
				errorProvider1.SetError( EinheitTextBox, "" )
			End If
		End Sub
		
		Private Sub PreisATSTextBox_Validating(sender As Object, e As CancelEventArgs)
			
			e.Cancel = False
			If String.IsNullOrEmpty( PreisATSTextBox.Text ) Then 
				e.Cancel = True
				errorProvider1.SetError( PreisATSTextBox, "The field PreisATS is required" ) 
			End If
			Dim v As Double
			Dim s As string = PreisATSTextBox.Text
			If Not Double.TryParse( s, v ) Then
				e.Cancel = True
				errorProvider1.SetError( PreisATSTextBox, "The field PreisATS must be Double." )
			End If
			If Not e.Cancel Then
				errorProvider1.SetError( PreisATSTextBox, "" )
			End If
		End Sub
		
		Private Sub PreisEuroTextBox_Validating(sender As Object, e As CancelEventArgs)
			
			e.Cancel = False
			If String.IsNullOrEmpty( PreisEuroTextBox.Text ) Then 
				e.Cancel = True
				errorProvider1.SetError( PreisEuroTextBox, "The field PreisEuro is required" ) 
			End If
			Dim v As Double
			Dim s As string = PreisEuroTextBox.Text
			If Not Double.TryParse( s, v ) Then
				e.Cancel = True
				errorProvider1.SetError( PreisEuroTextBox, "The field PreisEuro must be Double." )
			End If
			If Not e.Cancel Then
				errorProvider1.SetError( PreisEuroTextBox, "" )
			End If
		End Sub
		
		Private Sub PreisATS_BruttoTextBox_Validating(sender As Object, e As CancelEventArgs)
			
			e.Cancel = False
			If String.IsNullOrEmpty( PreisATS_BruttoTextBox.Text ) Then 
				e.Cancel = True
				errorProvider1.SetError( PreisATS_BruttoTextBox, "The field PreisATS_Brutto is required" ) 
			End If
			Dim v As Double
			Dim s As string = PreisATS_BruttoTextBox.Text
			If Not Double.TryParse( s, v ) Then
				e.Cancel = True
				errorProvider1.SetError( PreisATS_BruttoTextBox, "The field PreisATS_Brutto must be Double." )
			End If
			If Not e.Cancel Then
				errorProvider1.SetError( PreisATS_BruttoTextBox, "" )
			End If
		End Sub
		
		Private Sub EKPreisTextBox_Validating(sender As Object, e As CancelEventArgs)
			
			e.Cancel = False
			If String.IsNullOrEmpty( EKPreisTextBox.Text ) Then 
				e.Cancel = True
				errorProvider1.SetError( EKPreisTextBox, "The field EKPreis is required" ) 
			End If
			Dim v As Double
			Dim s As string = EKPreisTextBox.Text
			If Not Double.TryParse( s, v ) Then
				e.Cancel = True
				errorProvider1.SetError( EKPreisTextBox, "The field EKPreis must be Double." )
			End If
			If Not e.Cancel Then
				errorProvider1.SetError( EKPreisTextBox, "" )
			End If
		End Sub
		
		Private Sub LEKPreisTextBox_Validating(sender As Object, e As CancelEventArgs)
			
			e.Cancel = False
			If String.IsNullOrEmpty( LEKPreisTextBox.Text ) Then 
				e.Cancel = True
				errorProvider1.SetError( LEKPreisTextBox, "The field LEKPreis is required" ) 
			End If
			Dim v As Double
			Dim s As string = LEKPreisTextBox.Text
			If Not Double.TryParse( s, v ) Then
				e.Cancel = True
				errorProvider1.SetError( LEKPreisTextBox, "The field LEKPreis must be Double." )
			End If
			If Not e.Cancel Then
				errorProvider1.SetError( LEKPreisTextBox, "" )
			End If
		End Sub
		
		Private Sub LieferantNRTextBox_Validating(sender As Object, e As CancelEventArgs)
			
			e.Cancel = False
			If String.IsNullOrEmpty( LieferantNRTextBox.Text ) Then 
				e.Cancel = True
				errorProvider1.SetError( LieferantNRTextBox, "The field LieferantNR is required" ) 
			End If
			Dim v As Integer
			Dim s As string = LieferantNRTextBox.Text
			If Not Integer.TryParse( s, v ) Then
				e.Cancel = True
				errorProvider1.SetError( LieferantNRTextBox, "The field LieferantNR must be Integer." )
			End If
			If Not e.Cancel Then
				errorProvider1.SetError( LieferantNRTextBox, "" )
			End If
		End Sub
		
		Private Sub ArtKatNrTextBox_Validating(sender As Object, e As CancelEventArgs)
			
			e.Cancel = False
			If String.IsNullOrEmpty( ArtKatNrTextBox.Text ) Then 
				e.Cancel = True
				errorProvider1.SetError( ArtKatNrTextBox, "The field ArtKatNr is required" ) 
			End If
			Dim v As Integer
			Dim s As string = ArtKatNrTextBox.Text
			If Not Integer.TryParse( s, v ) Then
				e.Cancel = True
				errorProvider1.SetError( ArtKatNrTextBox, "The field ArtKatNr must be Integer." )
			End If
			If Not e.Cancel Then
				errorProvider1.SetError( ArtKatNrTextBox, "" )
			End If
		End Sub
		
		Private Sub MWSTTextBox_Validating(sender As Object, e As CancelEventArgs)
			
			e.Cancel = False
			If String.IsNullOrEmpty( MWSTTextBox.Text ) Then 
				e.Cancel = True
				errorProvider1.SetError( MWSTTextBox, "The field MWST is required" ) 
			End If
			Dim v As Integer
			Dim s As string = MWSTTextBox.Text
			If Not Integer.TryParse( s, v ) Then
				e.Cancel = True
				errorProvider1.SetError( MWSTTextBox, "The field MWST must be Integer." )
			End If
			If Not e.Cancel Then
				errorProvider1.SetError( MWSTTextBox, "" )
			End If
		End Sub
		
		Private Sub GewichtTextBox_Validating(sender As Object, e As CancelEventArgs)
			
			e.Cancel = False
			If String.IsNullOrEmpty( GewichtTextBox.Text ) Then 
				e.Cancel = True
				errorProvider1.SetError( GewichtTextBox, "The field Gewicht is required" ) 
			End If
			If Not e.Cancel Then
				errorProvider1.SetError( GewichtTextBox, "" )
			End If
		End Sub
		
		Private Sub PictureTextBox_Validating(sender As Object, e As CancelEventArgs)
			
			e.Cancel = False
			If String.IsNullOrEmpty( PictureTextBox.Text ) Then 
				e.Cancel = True
				errorProvider1.SetError( PictureTextBox, "The field Picture is required" ) 
			End If
			If Not e.Cancel Then
				errorProvider1.SetError( PictureTextBox, "" )
			End If
		End Sub
		
		Private Sub HerstellerNrTextBox_Validating(sender As Object, e As CancelEventArgs)
			
			e.Cancel = False
			If String.IsNullOrEmpty( HerstellerNrTextBox.Text ) Then 
				e.Cancel = True
				errorProvider1.SetError( HerstellerNrTextBox, "The field HerstellerNr is required" ) 
			End If
			Dim v As Integer
			Dim s As string = HerstellerNrTextBox.Text
			If Not Integer.TryParse( s, v ) Then
				e.Cancel = True
				errorProvider1.SetError( HerstellerNrTextBox, "The field HerstellerNr must be Integer." )
			End If
			If Not e.Cancel Then
				errorProvider1.SetError( HerstellerNrTextBox, "" )
			End If
		End Sub
		
		Private Sub ShopURLTextBox_Validating(sender As Object, e As CancelEventArgs)
			
			e.Cancel = False
			If String.IsNullOrEmpty( ShopURLTextBox.Text ) Then 
				e.Cancel = True
				errorProvider1.SetError( ShopURLTextBox, "The field ShopURL is required" ) 
			End If
			If Not e.Cancel Then
				errorProvider1.SetError( ShopURLTextBox, "" )
			End If
		End Sub
		
		Private Sub HerstellerURLTextBox_Validating(sender As Object, e As CancelEventArgs)
			
			e.Cancel = False
			If String.IsNullOrEmpty( HerstellerURLTextBox.Text ) Then 
				e.Cancel = True
				errorProvider1.SetError( HerstellerURLTextBox, "The field HerstellerURL is required" ) 
			End If
			If Not e.Cancel Then
				errorProvider1.SetError( HerstellerURLTextBox, "" )
			End If
		End Sub
		
		Private Sub ModifikationenTextBox_Validating(sender As Object, e As CancelEventArgs)
			
			e.Cancel = False
			If String.IsNullOrEmpty( ModifikationenTextBox.Text ) Then 
				e.Cancel = True
				errorProvider1.SetError( ModifikationenTextBox, "The field Modifikationen is required" ) 
			End If
			If Not e.Cancel Then
				errorProvider1.SetError( ModifikationenTextBox, "" )
			End If
		End Sub
		
		Private Sub HerstellerRabattTextBox_Validating(sender As Object, e As CancelEventArgs)
			
			e.Cancel = False
			If String.IsNullOrEmpty( HerstellerRabattTextBox.Text ) Then 
				e.Cancel = True
				errorProvider1.SetError( HerstellerRabattTextBox, "The field HerstellerRabatt is required" ) 
			End If
			Dim v As Double
			Dim s As string = HerstellerRabattTextBox.Text
			If Not Double.TryParse( s, v ) Then
				e.Cancel = True
				errorProvider1.SetError( HerstellerRabattTextBox, "The field HerstellerRabatt must be Double." )
			End If
			If Not e.Cancel Then
				errorProvider1.SetError( HerstellerRabattTextBox, "" )
			End If
		End Sub
		
		Private Sub HerstellerRabattTextTextBox_Validating(sender As Object, e As CancelEventArgs)
			
			e.Cancel = False
			If String.IsNullOrEmpty( HerstellerRabattTextTextBox.Text ) Then 
				e.Cancel = True
				errorProvider1.SetError( HerstellerRabattTextTextBox, "The field HerstellerRabattText is required" ) 
			End If
			If Not e.Cancel Then
				errorProvider1.SetError( HerstellerRabattTextTextBox, "" )
			End If
		End Sub
		
		Private Sub BruttoGewichtTextBox_Validating(sender As Object, e As CancelEventArgs)
			
			e.Cancel = False
			If String.IsNullOrEmpty( BruttoGewichtTextBox.Text ) Then 
				e.Cancel = True
				errorProvider1.SetError( BruttoGewichtTextBox, "The field BruttoGewicht is required" ) 
			End If
			Dim v As Double
			Dim s As string = BruttoGewichtTextBox.Text
			If Not Double.TryParse( s, v ) Then
				e.Cancel = True
				errorProvider1.SetError( BruttoGewichtTextBox, "The field BruttoGewicht must be Double." )
			End If
			If Not e.Cancel Then
				errorProvider1.SetError( BruttoGewichtTextBox, "" )
			End If
		End Sub
		
		Private Sub NettoGewichtTextBox_Validating(sender As Object, e As CancelEventArgs)
			
			e.Cancel = False
			If String.IsNullOrEmpty( NettoGewichtTextBox.Text ) Then 
				e.Cancel = True
				errorProvider1.SetError( NettoGewichtTextBox, "The field NettoGewicht is required" ) 
			End If
			Dim v As Double
			Dim s As string = NettoGewichtTextBox.Text
			If Not Double.TryParse( s, v ) Then
				e.Cancel = True
				errorProvider1.SetError( NettoGewichtTextBox, "The field NettoGewicht must be Double." )
			End If
			If Not e.Cancel Then
				errorProvider1.SetError( NettoGewichtTextBox, "" )
			End If
		End Sub
		
		Private Sub TaraGewichtTextBox_Validating(sender As Object, e As CancelEventArgs)
			
			e.Cancel = False
			If String.IsNullOrEmpty( TaraGewichtTextBox.Text ) Then 
				e.Cancel = True
				errorProvider1.SetError( TaraGewichtTextBox, "The field TaraGewicht is required" ) 
			End If
			Dim v As Double
			Dim s As string = TaraGewichtTextBox.Text
			If Not Double.TryParse( s, v ) Then
				e.Cancel = True
				errorProvider1.SetError( TaraGewichtTextBox, "The field TaraGewicht must be Double." )
			End If
			If Not e.Cancel Then
				errorProvider1.SetError( TaraGewichtTextBox, "" )
			End If
		End Sub
		
		Private Sub ProduktAktivOnlineTextBox_Validating(sender As Object, e As CancelEventArgs)
			
			e.Cancel = False
			If String.IsNullOrEmpty( ProduktAktivOnlineTextBox.Text ) Then 
				e.Cancel = True
				errorProvider1.SetError( ProduktAktivOnlineTextBox, "The field ProduktAktivOnline is required" ) 
			End If
			Dim v As Integer
			Dim s As string = ProduktAktivOnlineTextBox.Text
			If Not Integer.TryParse( s, v ) Then
				e.Cancel = True
				errorProvider1.SetError( ProduktAktivOnlineTextBox, "The field ProduktAktivOnline must be Integer." )
			End If
			If Not e.Cancel Then
				errorProvider1.SetError( ProduktAktivOnlineTextBox, "" )
			End If
		End Sub
		
		
		Private Sub bindingNavigatorAddNewItem_Click(sender As System.Object, e As System.EventArgs)
			grartikelBindingSource.AddNew()
		End Sub
		
	End Class
	
End Namespace
