' ++++++++++++++++++++++++++++++++++++++++++++++++++
' This code is generated by a tool and is provided "as is", without warranty of any kind,
' express or implied, including but not limited to the warranties of merchantability,
' fitness for a particular purpose and non-infringement.
' In no event shall the authors or copyright holders be liable for any claim, damages or
' other liability, whether in an action of contract, tort or otherwise, arising from,
' out of or in connection with the software or the use or other dealings in the software.
' ++++++++++++++++++++++++++++++++++++++++++++++++++
' 

Namespace MySQLTest
	
	<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
	Partial Class frmgrartikel
		Inherits System.Windows.Forms.Form
		
		'Form overrides dispose to clean up the component list.
		<System.Diagnostics.DebuggerNonUserCode()> _
		Protected Overrides Sub Dispose(ByVal disposing As Boolean)
			Try
			If disposing AndAlso components IsNot Nothing Then
				components.Dispose()
			End If
			Finally
			MyBase.Dispose(disposing)
			End Try
		End Sub
		
		'Required by the Windows Form Designer
		Private components As System.ComponentModel.IContainer
		
		'NOTE: The following procedure is required by the Windows Form Designer
		'It can be modified using the Windows Form Designer.  
		'Do not modify it using the code editor.
		<System.Diagnostics.DebuggerStepThrough()> _
		Private Sub InitializeComponent()
			Me.components = New System.ComponentModel.Container()
			Dim resources As System.ComponentModel.ComponentResourceManager = New System.ComponentModel.ComponentResourceManager(GetType(frmgrartikel))
			Me.BindingNavigator1 = New System.Windows.Forms.BindingNavigator(Me.components)
			Me.BindingNavigatorAddNewItem = New System.Windows.Forms.ToolStripButton()
			Me.BindingNavigatorCountItem = New System.Windows.Forms.ToolStripLabel()
			Me.BindingNavigatorDeleteItem = New System.Windows.Forms.ToolStripButton()
			Me.BindingNavigatorMoveFirstItem = New System.Windows.Forms.ToolStripButton()
			Me.BindingNavigatorMovePreviousItem = New System.Windows.Forms.ToolStripButton()
			Me.BindingNavigatorSeparator = New System.Windows.Forms.ToolStripSeparator()
			Me.BindingNavigatorPositionItem = New System.Windows.Forms.ToolStripTextBox()
			Me.BindingNavigatorSeparator1 = New System.Windows.Forms.ToolStripSeparator()
			Me.BindingNavigatorMoveNextItem = New System.Windows.Forms.ToolStripButton()
			Me.BindingNavigatorMoveLastItem = New System.Windows.Forms.ToolStripButton()
			Me.BindingNavigatorSeparator2 = New System.Windows.Forms.ToolStripSeparator()
			Me.ToolStripButton1 = New System.Windows.Forms.ToolStripButton()
			Me.ErrorProvider1 = New System.Windows.Forms.ErrorProvider(Me.components)
			Me.Panel1 = New System.Windows.Forms.Panel()
			
			Me.newDataSet = New NewDataSet()
			Me.grartikelBindingSource = New System.Windows.Forms.BindingSource(Me.components)
			Me.panel3 = New System.Windows.Forms.Panel()
			Me.panel4 = New System.Windows.Forms.Panel()
			Me.panel5 = New System.Windows.Forms.Panel()
			Me.panel6 = New System.Windows.Forms.Panel()
			
			CType(Me.BindingNavigator1, System.ComponentModel.ISupportInitialize).BeginInit()
			Me.BindingNavigator1.SuspendLayout()
			CType(Me.ErrorProvider1, System.ComponentModel.ISupportInitialize).BeginInit()
			Me.panel3.SuspendLayout()
			CType(Me.newDataSet, System.ComponentModel.ISupportInitialize).BeginInit()
			CType(Me.grartikelBindingSource, System.ComponentModel.ISupportInitialize).BeginInit()
			Me.Panel1.SuspendLayout()
			Me.SuspendLayout()
			'
			'BindingNavigator1
			'
			Me.BindingNavigator1.AddNewItem = Nothing
			Me.BindingNavigator1.CountItem = Me.BindingNavigatorCountItem
			Me.BindingNavigator1.DeleteItem = Me.BindingNavigatorDeleteItem
			Me.BindingNavigator1.Items.AddRange(New System.Windows.Forms.ToolStripItem() {Me.BindingNavigatorMoveFirstItem, Me.BindingNavigatorMovePreviousItem, Me.BindingNavigatorSeparator, Me.BindingNavigatorPositionItem, Me.BindingNavigatorCountItem, Me.BindingNavigatorSeparator1, Me.BindingNavigatorMoveNextItem, Me.BindingNavigatorMoveLastItem, Me.BindingNavigatorSeparator2, Me.BindingNavigatorAddNewItem, Me.BindingNavigatorDeleteItem, Me.ToolStripButton1})
			Me.BindingNavigator1.Location = New System.Drawing.Point(0, 0)
			Me.BindingNavigator1.MoveFirstItem = Me.BindingNavigatorMoveFirstItem
			Me.BindingNavigator1.MoveLastItem = Me.BindingNavigatorMoveLastItem
			Me.BindingNavigator1.MoveNextItem = Me.BindingNavigatorMoveNextItem
			Me.BindingNavigator1.MovePreviousItem = Me.BindingNavigatorMovePreviousItem
			Me.BindingNavigator1.Name = "BindingNavigator1"
			Me.bindingNavigator1.Padding = New System.Windows.Forms.Padding(10, 0, 10, 0)
			Me.BindingNavigator1.PositionItem = Me.BindingNavigatorPositionItem
			Me.BindingNavigator1.Size = New System.Drawing.Size(400, 25)
			Me.BindingNavigator1.TabIndex = 0
			Me.BindingNavigator1.Text = "BindingNavigator1"
			'
			'BindingNavigatorAddNewItem
			'
			Me.BindingNavigatorAddNewItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image
			Me.BindingNavigatorAddNewItem.Image = CType(resources.GetObject("BindingNavigatorAddNewItem.Image"), System.Drawing.Image)
			Me.BindingNavigatorAddNewItem.Name = "BindingNavigatorAddNewItem"
			Me.BindingNavigatorAddNewItem.RightToLeftAutoMirrorImage = True
			Me.BindingNavigatorAddNewItem.Size = New System.Drawing.Size(23, 22)
			Me.BindingNavigatorAddNewItem.Text = "Add new"
			AddHandler Me.BindingNavigatorAddNewItem.Click, AddressOf Me.bindingNavigatorAddNewItem_Click
			'
			'BindingNavigatorCountItem
			'
			Me.BindingNavigatorCountItem.Name = "BindingNavigatorCountItem"
			Me.BindingNavigatorCountItem.Size = New System.Drawing.Size(35, 22)
			Me.BindingNavigatorCountItem.Text = "of {0}"
			Me.BindingNavigatorCountItem.ToolTipText = "Total number of items"
			'
			'BindingNavigatorDeleteItem
			'
			Me.BindingNavigatorDeleteItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image
			Me.BindingNavigatorDeleteItem.Image = CType(resources.GetObject("BindingNavigatorDeleteItem.Image"), System.Drawing.Image)
			Me.BindingNavigatorDeleteItem.Name = "BindingNavigatorDeleteItem"
			Me.BindingNavigatorDeleteItem.RightToLeftAutoMirrorImage = True
			Me.BindingNavigatorDeleteItem.Size = New System.Drawing.Size(23, 22)
			Me.BindingNavigatorDeleteItem.Text = "Delete"
			'
			'BindingNavigatorMoveFirstItem
			'
			Me.BindingNavigatorMoveFirstItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image
			Me.BindingNavigatorMoveFirstItem.Image = CType(resources.GetObject("BindingNavigatorMoveFirstItem.Image"), System.Drawing.Image)
			Me.BindingNavigatorMoveFirstItem.Name = "BindingNavigatorMoveFirstItem"
			Me.BindingNavigatorMoveFirstItem.RightToLeftAutoMirrorImage = True
			Me.BindingNavigatorMoveFirstItem.Size = New System.Drawing.Size(23, 22)
			Me.BindingNavigatorMoveFirstItem.Text = "Move first"
			'
			'BindingNavigatorMovePreviousItem
			'
			Me.BindingNavigatorMovePreviousItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image
			Me.BindingNavigatorMovePreviousItem.Image = CType(resources.GetObject("BindingNavigatorMovePreviousItem.Image"), System.Drawing.Image)
			Me.BindingNavigatorMovePreviousItem.Name = "BindingNavigatorMovePreviousItem"
			Me.BindingNavigatorMovePreviousItem.RightToLeftAutoMirrorImage = True
			Me.BindingNavigatorMovePreviousItem.Size = New System.Drawing.Size(23, 22)
			Me.BindingNavigatorMovePreviousItem.Text = "Move previous"
			'
			'BindingNavigatorSeparator
			'
			Me.BindingNavigatorSeparator.Name = "BindingNavigatorSeparator"
			Me.BindingNavigatorSeparator.Size = New System.Drawing.Size(6, 25)
			'
			'BindingNavigatorPositionItem
			'
			Me.BindingNavigatorPositionItem.AccessibleName = "Position"
			Me.BindingNavigatorPositionItem.AutoSize = False
			Me.BindingNavigatorPositionItem.Name = "BindingNavigatorPositionItem"
			Me.BindingNavigatorPositionItem.Size = New System.Drawing.Size(50, 23)
			Me.BindingNavigatorPositionItem.Text = "0"
			Me.BindingNavigatorPositionItem.ToolTipText = "Current position"
			'
			'BindingNavigatorSeparator1
			'
			Me.BindingNavigatorSeparator1.Name = "BindingNavigatorSeparator1"
			Me.BindingNavigatorSeparator1.Size = New System.Drawing.Size(6, 25)
			'
			'BindingNavigatorMoveNextItem
			'
			Me.BindingNavigatorMoveNextItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image
			Me.BindingNavigatorMoveNextItem.Image = CType(resources.GetObject("BindingNavigatorMoveNextItem.Image"), System.Drawing.Image)
			Me.BindingNavigatorMoveNextItem.Name = "BindingNavigatorMoveNextItem"
			Me.BindingNavigatorMoveNextItem.RightToLeftAutoMirrorImage = True
			Me.BindingNavigatorMoveNextItem.Size = New System.Drawing.Size(23, 22)
			Me.BindingNavigatorMoveNextItem.Text = "Move next"
			'
			'BindingNavigatorMoveLastItem
			'
			Me.BindingNavigatorMoveLastItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image
			Me.BindingNavigatorMoveLastItem.Image = CType(resources.GetObject("BindingNavigatorMoveLastItem.Image"), System.Drawing.Image)
			Me.BindingNavigatorMoveLastItem.Name = "BindingNavigatorMoveLastItem"
			Me.BindingNavigatorMoveLastItem.RightToLeftAutoMirrorImage = True
			Me.BindingNavigatorMoveLastItem.Size = New System.Drawing.Size(23, 22)
			Me.BindingNavigatorMoveLastItem.Text = "Move last"
			'
			'BindingNavigatorSeparator2
			'
			Me.BindingNavigatorSeparator2.Name = "BindingNavigatorSeparator2"
			Me.BindingNavigatorSeparator2.Size = New System.Drawing.Size(6, 25)
			'
			'ToolStripButton1
			'
			Me.ToolStripButton1.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image
			Me.ToolStripButton1.Image = CType(resources.GetObject("ToolStripButton1.Image"), System.Drawing.Image)
			Me.ToolStripButton1.ImageTransparentColor = System.Drawing.Color.Magenta
			Me.ToolStripButton1.Name = "ToolStripButton1"
			Me.ToolStripButton1.Size = New System.Drawing.Size(23, 22)
			Me.ToolStripButton1.Text = "Save"
			'
			'ErrorProvider1
			'
			Me.ErrorProvider1.ContainerControl = Me
			'
			'Panel1
			'
			Me.Panel1.AutoScroll = True
			Me.Panel1.Dock = System.Windows.Forms.DockStyle.Fill
			Me.Panel1.Location = New System.Drawing.Point(0, 25)
			Me.Panel1.Margin = new System.Windows.Forms.Padding(10, 3, 10, 3)
			Me.Panel1.Name = "Panel1"
			Me.Panel1.Size = New System.Drawing.Size(656, 183)
			Me.Panel1.TabIndex = 1
			Me.Panel1.AutoSize = True
			
			Me.bindingNavigator1.BindingSource = Me.grartikelBindingSource
			'
			'newDataSet
			'
			Me.newDataSet.DataSetName = "NewDataSet"
			Me.newDataSet.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema
			'
			'tableBindingSource
			' 
			Me.grartikelBindingSource.DataMember = "grartikel"
			Me.grartikelBindingSource.DataSource = Me.newDataSet
			'
			' ArtNrLabel
			'
			Me.ArtNrLabel = New System.Windows.Forms.Label()
			Me.ArtNrLabel.AutoSize = True
			Me.ArtNrLabel.Location = New System.Drawing.Point( 123, 50 )
			Me.ArtNrLabel.Name = "ArtNrLabel"
			Me.ArtNrLabel.Size = New System.Drawing.Size( 31, 13 )
			Me.ArtNrLabel.TabIndex = 1
			Me.ArtNrLabel.Text = "ArtNr"
			Me.Panel1.Controls.Add( Me.ArtNrLabel )
			'
			' ArtNrTextBox
			'
			Me.ArtNrTextBox = New System.Windows.Forms.TextBox()
			Me.ArtNrTextBox.DataBindings.Add(New System.Windows.Forms.Binding("Text", Me.grartikelBindingSource, "ArtNr", true ))
			Me.ArtNrTextBox.Location = New System.Drawing.Point( 164, 50 )
			Me.ArtNrTextBox.Name = "ArtNrTextBox"
			Me.ArtNrTextBox.Size = New System.Drawing.Size( 100, 20 )
			Me.ArtNrTextBox.TabIndex = 2
			AddHandler Me.ArtNrTextBox.Validating, AddressOf Me.ArtNrTextBox_Validating
			Me.Panel1.Controls.Add( Me.ArtNrTextBox)
			'
			' EANLabel
			'
			Me.EANLabel = New System.Windows.Forms.Label()
			Me.EANLabel.AutoSize = True
			Me.EANLabel.Location = New System.Drawing.Point( 125, 76 )
			Me.EANLabel.Name = "EANLabel"
			Me.EANLabel.Size = New System.Drawing.Size( 29, 13 )
			Me.EANLabel.TabIndex = 3
			Me.EANLabel.Text = "EAN"
			Me.Panel1.Controls.Add( Me.EANLabel )
			'
			' EANTextBox
			'
			Me.EANTextBox = New System.Windows.Forms.TextBox()
			Me.EANTextBox.DataBindings.Add(New System.Windows.Forms.Binding("Text", Me.grartikelBindingSource, "EAN", true ))
			Me.EANTextBox.Location = New System.Drawing.Point( 164, 76 )
			Me.EANTextBox.Name = "EANTextBox"
			Me.EANTextBox.Size = New System.Drawing.Size( 100, 20 )
			Me.EANTextBox.TabIndex = 4
			AddHandler Me.EANTextBox.Validating, AddressOf Me.EANTextBox_Validating
			Me.Panel1.Controls.Add( Me.EANTextBox)
			'
			' BarcodeLabel
			'
			Me.BarcodeLabel = New System.Windows.Forms.Label()
			Me.BarcodeLabel.AutoSize = True
			Me.BarcodeLabel.Location = New System.Drawing.Point( 107, 102 )
			Me.BarcodeLabel.Name = "BarcodeLabel"
			Me.BarcodeLabel.Size = New System.Drawing.Size( 47, 13 )
			Me.BarcodeLabel.TabIndex = 5
			Me.BarcodeLabel.Text = "Barcode"
			Me.Panel1.Controls.Add( Me.BarcodeLabel )
			'
			' BarcodeTextBox
			'
			Me.BarcodeTextBox = New System.Windows.Forms.TextBox()
			Me.BarcodeTextBox.DataBindings.Add(New System.Windows.Forms.Binding("Text", Me.grartikelBindingSource, "Barcode", true ))
			Me.BarcodeTextBox.Location = New System.Drawing.Point( 164, 102 )
			Me.BarcodeTextBox.Name = "BarcodeTextBox"
			Me.BarcodeTextBox.Size = New System.Drawing.Size( 100, 20 )
			Me.BarcodeTextBox.TabIndex = 6
			AddHandler Me.BarcodeTextBox.Validating, AddressOf Me.BarcodeTextBox_Validating
			Me.Panel1.Controls.Add( Me.BarcodeTextBox)
			'
			' BezeichnungLabel
			'
			Me.BezeichnungLabel = New System.Windows.Forms.Label()
			Me.BezeichnungLabel.AutoSize = True
			Me.BezeichnungLabel.Location = New System.Drawing.Point( 85, 128 )
			Me.BezeichnungLabel.Name = "BezeichnungLabel"
			Me.BezeichnungLabel.Size = New System.Drawing.Size( 69, 13 )
			Me.BezeichnungLabel.TabIndex = 7
			Me.BezeichnungLabel.Text = "Bezeichnung"
			Me.Panel1.Controls.Add( Me.BezeichnungLabel )
			'
			' BezeichnungTextBox
			'
			Me.BezeichnungTextBox = New System.Windows.Forms.TextBox()
			Me.BezeichnungTextBox.DataBindings.Add(New System.Windows.Forms.Binding("Text", Me.grartikelBindingSource, "Bezeichnung", true ))
			Me.BezeichnungTextBox.Location = New System.Drawing.Point( 164, 128 )
			Me.BezeichnungTextBox.Name = "BezeichnungTextBox"
			Me.BezeichnungTextBox.Size = New System.Drawing.Size( 100, 20 )
			Me.BezeichnungTextBox.TabIndex = 8
			AddHandler Me.BezeichnungTextBox.Validating, AddressOf Me.BezeichnungTextBox_Validating
			Me.Panel1.Controls.Add( Me.BezeichnungTextBox)
			'
			' Bezeichnung1Label
			'
			Me.Bezeichnung1Label = New System.Windows.Forms.Label()
			Me.Bezeichnung1Label.AutoSize = True
			Me.Bezeichnung1Label.Location = New System.Drawing.Point( 79, 154 )
			Me.Bezeichnung1Label.Name = "Bezeichnung1Label"
			Me.Bezeichnung1Label.Size = New System.Drawing.Size( 75, 13 )
			Me.Bezeichnung1Label.TabIndex = 9
			Me.Bezeichnung1Label.Text = "Bezeichnung1"
			Me.Panel1.Controls.Add( Me.Bezeichnung1Label )
			'
			' Bezeichnung1TextBox
			'
			Me.Bezeichnung1TextBox = New System.Windows.Forms.TextBox()
			Me.Bezeichnung1TextBox.DataBindings.Add(New System.Windows.Forms.Binding("Text", Me.grartikelBindingSource, "Bezeichnung1", true ))
			Me.Bezeichnung1TextBox.Location = New System.Drawing.Point( 164, 154 )
			Me.Bezeichnung1TextBox.Name = "Bezeichnung1TextBox"
			Me.Bezeichnung1TextBox.Size = New System.Drawing.Size( 100, 20 )
			Me.Bezeichnung1TextBox.TabIndex = 10
			AddHandler Me.Bezeichnung1TextBox.Validating, AddressOf Me.Bezeichnung1TextBox_Validating
			Me.Panel1.Controls.Add( Me.Bezeichnung1TextBox)
			'
			' BeschreibungLabel
			'
			Me.BeschreibungLabel = New System.Windows.Forms.Label()
			Me.BeschreibungLabel.AutoSize = True
			Me.BeschreibungLabel.Location = New System.Drawing.Point( 82, 180 )
			Me.BeschreibungLabel.Name = "BeschreibungLabel"
			Me.BeschreibungLabel.Size = New System.Drawing.Size( 72, 13 )
			Me.BeschreibungLabel.TabIndex = 11
			Me.BeschreibungLabel.Text = "Beschreibung"
			Me.Panel1.Controls.Add( Me.BeschreibungLabel )
			'
			' BeschreibungTextBox
			'
			Me.BeschreibungTextBox = New System.Windows.Forms.TextBox()
			Me.BeschreibungTextBox.DataBindings.Add(New System.Windows.Forms.Binding("Text", Me.grartikelBindingSource, "Beschreibung", true ))
			Me.BeschreibungTextBox.Location = New System.Drawing.Point( 164, 180 )
			Me.BeschreibungTextBox.Name = "BeschreibungTextBox"
			Me.BeschreibungTextBox.Size = New System.Drawing.Size( 100, 20 )
			Me.BeschreibungTextBox.TabIndex = 12
			AddHandler Me.BeschreibungTextBox.Validating, AddressOf Me.BeschreibungTextBox_Validating
			Me.Panel1.Controls.Add( Me.BeschreibungTextBox)
			'
			' EinheitLabel
			'
			Me.EinheitLabel = New System.Windows.Forms.Label()
			Me.EinheitLabel.AutoSize = True
			Me.EinheitLabel.Location = New System.Drawing.Point( 115, 206 )
			Me.EinheitLabel.Name = "EinheitLabel"
			Me.EinheitLabel.Size = New System.Drawing.Size( 39, 13 )
			Me.EinheitLabel.TabIndex = 13
			Me.EinheitLabel.Text = "Einheit"
			Me.Panel1.Controls.Add( Me.EinheitLabel )
			'
			' EinheitTextBox
			'
			Me.EinheitTextBox = New System.Windows.Forms.TextBox()
			Me.EinheitTextBox.DataBindings.Add(New System.Windows.Forms.Binding("Text", Me.grartikelBindingSource, "Einheit", true ))
			Me.EinheitTextBox.Location = New System.Drawing.Point( 164, 206 )
			Me.EinheitTextBox.Name = "EinheitTextBox"
			Me.EinheitTextBox.Size = New System.Drawing.Size( 100, 20 )
			Me.EinheitTextBox.TabIndex = 14
			AddHandler Me.EinheitTextBox.Validating, AddressOf Me.EinheitTextBox_Validating
			Me.Panel1.Controls.Add( Me.EinheitTextBox)
			'
			' PreisATSLabel
			'
			Me.PreisATSLabel = New System.Windows.Forms.Label()
			Me.PreisATSLabel.AutoSize = True
			Me.PreisATSLabel.Location = New System.Drawing.Point( 103, 232 )
			Me.PreisATSLabel.Name = "PreisATSLabel"
			Me.PreisATSLabel.Size = New System.Drawing.Size( 51, 13 )
			Me.PreisATSLabel.TabIndex = 15
			Me.PreisATSLabel.Text = "PreisATS"
			Me.Panel1.Controls.Add( Me.PreisATSLabel )
			'
			' PreisATSTextBox
			'
			Me.PreisATSTextBox = New System.Windows.Forms.TextBox()
			Me.PreisATSTextBox.DataBindings.Add(New System.Windows.Forms.Binding("Text", Me.grartikelBindingSource, "PreisATS", true ))
			Me.PreisATSTextBox.Location = New System.Drawing.Point( 164, 232 )
			Me.PreisATSTextBox.Name = "PreisATSTextBox"
			Me.PreisATSTextBox.Size = New System.Drawing.Size( 100, 20 )
			Me.PreisATSTextBox.TabIndex = 16
			AddHandler Me.PreisATSTextBox.Validating, AddressOf Me.PreisATSTextBox_Validating
			Me.Panel1.Controls.Add( Me.PreisATSTextBox)
			'
			' PreisEuroLabel
			'
			Me.PreisEuroLabel = New System.Windows.Forms.Label()
			Me.PreisEuroLabel.AutoSize = True
			Me.PreisEuroLabel.Location = New System.Drawing.Point( 102, 258 )
			Me.PreisEuroLabel.Name = "PreisEuroLabel"
			Me.PreisEuroLabel.Size = New System.Drawing.Size( 52, 13 )
			Me.PreisEuroLabel.TabIndex = 17
			Me.PreisEuroLabel.Text = "PreisEuro"
			Me.Panel1.Controls.Add( Me.PreisEuroLabel )
			'
			' PreisEuroTextBox
			'
			Me.PreisEuroTextBox = New System.Windows.Forms.TextBox()
			Me.PreisEuroTextBox.DataBindings.Add(New System.Windows.Forms.Binding("Text", Me.grartikelBindingSource, "PreisEuro", true ))
			Me.PreisEuroTextBox.Location = New System.Drawing.Point( 164, 258 )
			Me.PreisEuroTextBox.Name = "PreisEuroTextBox"
			Me.PreisEuroTextBox.Size = New System.Drawing.Size( 100, 20 )
			Me.PreisEuroTextBox.TabIndex = 18
			AddHandler Me.PreisEuroTextBox.Validating, AddressOf Me.PreisEuroTextBox_Validating
			Me.Panel1.Controls.Add( Me.PreisEuroTextBox)
			'
			' PreisATS_BruttoLabel
			'
			Me.PreisATS_BruttoLabel = New System.Windows.Forms.Label()
			Me.PreisATS_BruttoLabel.AutoSize = True
			Me.PreisATS_BruttoLabel.Location = New System.Drawing.Point( 69, 284 )
			Me.PreisATS_BruttoLabel.Name = "PreisATS_BruttoLabel"
			Me.PreisATS_BruttoLabel.Size = New System.Drawing.Size( 85, 13 )
			Me.PreisATS_BruttoLabel.TabIndex = 19
			Me.PreisATS_BruttoLabel.Text = "PreisATS_Brutto"
			Me.Panel1.Controls.Add( Me.PreisATS_BruttoLabel )
			'
			' PreisATS_BruttoTextBox
			'
			Me.PreisATS_BruttoTextBox = New System.Windows.Forms.TextBox()
			Me.PreisATS_BruttoTextBox.DataBindings.Add(New System.Windows.Forms.Binding("Text", Me.grartikelBindingSource, "PreisATS_Brutto", true ))
			Me.PreisATS_BruttoTextBox.Location = New System.Drawing.Point( 164, 284 )
			Me.PreisATS_BruttoTextBox.Name = "PreisATS_BruttoTextBox"
			Me.PreisATS_BruttoTextBox.Size = New System.Drawing.Size( 100, 20 )
			Me.PreisATS_BruttoTextBox.TabIndex = 20
			AddHandler Me.PreisATS_BruttoTextBox.Validating, AddressOf Me.PreisATS_BruttoTextBox_Validating
			Me.Panel1.Controls.Add( Me.PreisATS_BruttoTextBox)
			'
			' LagerArtikelLabel
			'
			Me.LagerArtikelLabel = New System.Windows.Forms.Label()
			Me.LagerArtikelLabel.AutoSize = True
			Me.LagerArtikelLabel.Location = New System.Drawing.Point( 91, 310 )
			Me.LagerArtikelLabel.Name = "LagerArtikelLabel"
			Me.LagerArtikelLabel.Size = New System.Drawing.Size( 63, 13 )
			Me.LagerArtikelLabel.TabIndex = 21
			Me.LagerArtikelLabel.Text = "LagerArtikel"
			Me.Panel1.Controls.Add( Me.LagerArtikelLabel )
			'
			'LagerArtikelCheckBox
			'
			Me.LagerArtikelCheckBox = New System.Windows.Forms.CheckBox()
			Me.LagerArtikelCheckBox.AutoSize = True
			Me.LagerArtikelCheckBox.Location = New System.Drawing.Point(164, 313)
			Me.LagerArtikelCheckBox.Name = "LagerArtikelCheckBox"
			Me.LagerArtikelCheckBox.Size = New System.Drawing.Size(15, 14)
			Me.LagerArtikelCheckBox.TabIndex = 22
			Me.LagerArtikelCheckBox.UseVisualStyleBackColor = True
			Me.Panel1.Controls.Add( Me.LagerArtikelCheckBox )
			Me.LagerArtikelCheckBox.DataBindings.Add(New System.Windows.Forms.Binding("Checked", Me.grartikelBindingSource, "LagerArtikel", True))
			'
			' EKPreisLabel
			'
			Me.EKPreisLabel = New System.Windows.Forms.Label()
			Me.EKPreisLabel.AutoSize = True
			Me.EKPreisLabel.Location = New System.Drawing.Point( 110, 336 )
			Me.EKPreisLabel.Name = "EKPreisLabel"
			Me.EKPreisLabel.Size = New System.Drawing.Size( 44, 13 )
			Me.EKPreisLabel.TabIndex = 23
			Me.EKPreisLabel.Text = "EKPreis"
			Me.Panel1.Controls.Add( Me.EKPreisLabel )
			'
			' EKPreisTextBox
			'
			Me.EKPreisTextBox = New System.Windows.Forms.TextBox()
			Me.EKPreisTextBox.DataBindings.Add(New System.Windows.Forms.Binding("Text", Me.grartikelBindingSource, "EKPreis", true ))
			Me.EKPreisTextBox.Location = New System.Drawing.Point( 164, 336 )
			Me.EKPreisTextBox.Name = "EKPreisTextBox"
			Me.EKPreisTextBox.Size = New System.Drawing.Size( 100, 20 )
			Me.EKPreisTextBox.TabIndex = 24
			AddHandler Me.EKPreisTextBox.Validating, AddressOf Me.EKPreisTextBox_Validating
			Me.Panel1.Controls.Add( Me.EKPreisTextBox)
			'
			' LEKPreisLabel
			'
			Me.LEKPreisLabel = New System.Windows.Forms.Label()
			Me.LEKPreisLabel.AutoSize = True
			Me.LEKPreisLabel.Location = New System.Drawing.Point( 104, 362 )
			Me.LEKPreisLabel.Name = "LEKPreisLabel"
			Me.LEKPreisLabel.Size = New System.Drawing.Size( 50, 13 )
			Me.LEKPreisLabel.TabIndex = 25
			Me.LEKPreisLabel.Text = "LEKPreis"
			Me.Panel1.Controls.Add( Me.LEKPreisLabel )
			'
			' LEKPreisTextBox
			'
			Me.LEKPreisTextBox = New System.Windows.Forms.TextBox()
			Me.LEKPreisTextBox.DataBindings.Add(New System.Windows.Forms.Binding("Text", Me.grartikelBindingSource, "LEKPreis", true ))
			Me.LEKPreisTextBox.Location = New System.Drawing.Point( 164, 362 )
			Me.LEKPreisTextBox.Name = "LEKPreisTextBox"
			Me.LEKPreisTextBox.Size = New System.Drawing.Size( 100, 20 )
			Me.LEKPreisTextBox.TabIndex = 26
			AddHandler Me.LEKPreisTextBox.Validating, AddressOf Me.LEKPreisTextBox_Validating
			Me.Panel1.Controls.Add( Me.LEKPreisTextBox)
			'
			' SeriennummerLabel
			'
			Me.SeriennummerLabel = New System.Windows.Forms.Label()
			Me.SeriennummerLabel.AutoSize = True
			Me.SeriennummerLabel.Location = New System.Drawing.Point( 80, 388 )
			Me.SeriennummerLabel.Name = "SeriennummerLabel"
			Me.SeriennummerLabel.Size = New System.Drawing.Size( 74, 13 )
			Me.SeriennummerLabel.TabIndex = 27
			Me.SeriennummerLabel.Text = "Seriennummer"
			Me.Panel1.Controls.Add( Me.SeriennummerLabel )
			'
			'SeriennummerCheckBox
			'
			Me.SeriennummerCheckBox = New System.Windows.Forms.CheckBox()
			Me.SeriennummerCheckBox.AutoSize = True
			Me.SeriennummerCheckBox.Location = New System.Drawing.Point(164, 391)
			Me.SeriennummerCheckBox.Name = "SeriennummerCheckBox"
			Me.SeriennummerCheckBox.Size = New System.Drawing.Size(15, 14)
			Me.SeriennummerCheckBox.TabIndex = 28
			Me.SeriennummerCheckBox.UseVisualStyleBackColor = True
			Me.Panel1.Controls.Add( Me.SeriennummerCheckBox )
			Me.SeriennummerCheckBox.DataBindings.Add(New System.Windows.Forms.Binding("Checked", Me.grartikelBindingSource, "Seriennummer", True))
			'
			' LieferantNRLabel
			'
			Me.LieferantNRLabel = New System.Windows.Forms.Label()
			Me.LieferantNRLabel.AutoSize = True
			Me.LieferantNRLabel.Location = New System.Drawing.Point( 90, 414 )
			Me.LieferantNRLabel.Name = "LieferantNRLabel"
			Me.LieferantNRLabel.Size = New System.Drawing.Size( 64, 13 )
			Me.LieferantNRLabel.TabIndex = 29
			Me.LieferantNRLabel.Text = "LieferantNR"
			Me.Panel1.Controls.Add( Me.LieferantNRLabel )
			'
			' LieferantNRTextBox
			'
			Me.LieferantNRTextBox = New System.Windows.Forms.TextBox()
			Me.LieferantNRTextBox.DataBindings.Add(New System.Windows.Forms.Binding("Text", Me.grartikelBindingSource, "LieferantNR", true ))
			Me.LieferantNRTextBox.Location = New System.Drawing.Point( 164, 414 )
			Me.LieferantNRTextBox.Name = "LieferantNRTextBox"
			Me.LieferantNRTextBox.Size = New System.Drawing.Size( 100, 20 )
			Me.LieferantNRTextBox.TabIndex = 30
			AddHandler Me.LieferantNRTextBox.Validating, AddressOf Me.LieferantNRTextBox_Validating
			Me.Panel1.Controls.Add( Me.LieferantNRTextBox)
			'
			' SetArtikelLabel
			'
			Me.SetArtikelLabel = New System.Windows.Forms.Label()
			Me.SetArtikelLabel.AutoSize = True
			Me.SetArtikelLabel.Location = New System.Drawing.Point( 102, 440 )
			Me.SetArtikelLabel.Name = "SetArtikelLabel"
			Me.SetArtikelLabel.Size = New System.Drawing.Size( 52, 13 )
			Me.SetArtikelLabel.TabIndex = 31
			Me.SetArtikelLabel.Text = "SetArtikel"
			Me.Panel1.Controls.Add( Me.SetArtikelLabel )
			'
			'SetArtikelCheckBox
			'
			Me.SetArtikelCheckBox = New System.Windows.Forms.CheckBox()
			Me.SetArtikelCheckBox.AutoSize = True
			Me.SetArtikelCheckBox.Location = New System.Drawing.Point(164, 443)
			Me.SetArtikelCheckBox.Name = "SetArtikelCheckBox"
			Me.SetArtikelCheckBox.Size = New System.Drawing.Size(15, 14)
			Me.SetArtikelCheckBox.TabIndex = 32
			Me.SetArtikelCheckBox.UseVisualStyleBackColor = True
			Me.Panel1.Controls.Add( Me.SetArtikelCheckBox )
			Me.SetArtikelCheckBox.DataBindings.Add(New System.Windows.Forms.Binding("Checked", Me.grartikelBindingSource, "SetArtikel", True))
			'
			' ArtKatNrLabel
			'
			Me.ArtKatNrLabel = New System.Windows.Forms.Label()
			Me.ArtKatNrLabel.AutoSize = True
			Me.ArtKatNrLabel.Location = New System.Drawing.Point( 107, 466 )
			Me.ArtKatNrLabel.Name = "ArtKatNrLabel"
			Me.ArtKatNrLabel.Size = New System.Drawing.Size( 47, 13 )
			Me.ArtKatNrLabel.TabIndex = 33
			Me.ArtKatNrLabel.Text = "ArtKatNr"
			Me.Panel1.Controls.Add( Me.ArtKatNrLabel )
			'
			' ArtKatNrTextBox
			'
			Me.ArtKatNrTextBox = New System.Windows.Forms.TextBox()
			Me.ArtKatNrTextBox.DataBindings.Add(New System.Windows.Forms.Binding("Text", Me.grartikelBindingSource, "ArtKatNr", true ))
			Me.ArtKatNrTextBox.Location = New System.Drawing.Point( 164, 466 )
			Me.ArtKatNrTextBox.Name = "ArtKatNrTextBox"
			Me.ArtKatNrTextBox.Size = New System.Drawing.Size( 100, 20 )
			Me.ArtKatNrTextBox.TabIndex = 34
			AddHandler Me.ArtKatNrTextBox.Validating, AddressOf Me.ArtKatNrTextBox_Validating
			Me.Panel1.Controls.Add( Me.ArtKatNrTextBox)
			'
			' MWSTLabel
			'
			Me.MWSTLabel = New System.Windows.Forms.Label()
			Me.MWSTLabel.AutoSize = True
			Me.MWSTLabel.Location = New System.Drawing.Point( 437, 50 )
			Me.MWSTLabel.Name = "MWSTLabel"
			Me.MWSTLabel.Size = New System.Drawing.Size( 41, 13 )
			Me.MWSTLabel.TabIndex = 35
			Me.MWSTLabel.Text = "MWST"
			Me.Panel1.Controls.Add( Me.MWSTLabel )
			'
			' MWSTTextBox
			'
			Me.MWSTTextBox = New System.Windows.Forms.TextBox()
			Me.MWSTTextBox.DataBindings.Add(New System.Windows.Forms.Binding("Text", Me.grartikelBindingSource, "MWST", true ))
			Me.MWSTTextBox.Location = New System.Drawing.Point( 488, 50 )
			Me.MWSTTextBox.Name = "MWSTTextBox"
			Me.MWSTTextBox.Size = New System.Drawing.Size( 100, 20 )
			Me.MWSTTextBox.TabIndex = 36
			AddHandler Me.MWSTTextBox.Validating, AddressOf Me.MWSTTextBox_Validating
			Me.Panel1.Controls.Add( Me.MWSTTextBox)
			'
			' GewichtLabel
			'
			Me.GewichtLabel = New System.Windows.Forms.Label()
			Me.GewichtLabel.AutoSize = True
			Me.GewichtLabel.Location = New System.Drawing.Point( 432, 76 )
			Me.GewichtLabel.Name = "GewichtLabel"
			Me.GewichtLabel.Size = New System.Drawing.Size( 46, 13 )
			Me.GewichtLabel.TabIndex = 37
			Me.GewichtLabel.Text = "Gewicht"
			Me.Panel1.Controls.Add( Me.GewichtLabel )
			'
			' GewichtTextBox
			'
			Me.GewichtTextBox = New System.Windows.Forms.TextBox()
			Me.GewichtTextBox.DataBindings.Add(New System.Windows.Forms.Binding("Text", Me.grartikelBindingSource, "Gewicht", true ))
			Me.GewichtTextBox.Location = New System.Drawing.Point( 488, 76 )
			Me.GewichtTextBox.Name = "GewichtTextBox"
			Me.GewichtTextBox.Size = New System.Drawing.Size( 100, 20 )
			Me.GewichtTextBox.TabIndex = 38
			AddHandler Me.GewichtTextBox.Validating, AddressOf Me.GewichtTextBox_Validating
			Me.Panel1.Controls.Add( Me.GewichtTextBox)
			'
			' PictureLabel
			'
			Me.PictureLabel = New System.Windows.Forms.Label()
			Me.PictureLabel.AutoSize = True
			Me.PictureLabel.Location = New System.Drawing.Point( 438, 102 )
			Me.PictureLabel.Name = "PictureLabel"
			Me.PictureLabel.Size = New System.Drawing.Size( 40, 13 )
			Me.PictureLabel.TabIndex = 39
			Me.PictureLabel.Text = "Picture"
			Me.Panel1.Controls.Add( Me.PictureLabel )
			'
			' PictureTextBox
			'
			Me.PictureTextBox = New System.Windows.Forms.TextBox()
			Me.PictureTextBox.DataBindings.Add(New System.Windows.Forms.Binding("Text", Me.grartikelBindingSource, "Picture", true ))
			Me.PictureTextBox.Location = New System.Drawing.Point( 488, 102 )
			Me.PictureTextBox.Name = "PictureTextBox"
			Me.PictureTextBox.Size = New System.Drawing.Size( 100, 20 )
			Me.PictureTextBox.TabIndex = 40
			AddHandler Me.PictureTextBox.Validating, AddressOf Me.PictureTextBox_Validating
			Me.Panel1.Controls.Add( Me.PictureTextBox)
			'
			' HerstellerNrLabel
			'
			Me.HerstellerNrLabel = New System.Windows.Forms.Label()
			Me.HerstellerNrLabel.AutoSize = True
			Me.HerstellerNrLabel.Location = New System.Drawing.Point( 416, 128 )
			Me.HerstellerNrLabel.Name = "HerstellerNrLabel"
			Me.HerstellerNrLabel.Size = New System.Drawing.Size( 62, 13 )
			Me.HerstellerNrLabel.TabIndex = 41
			Me.HerstellerNrLabel.Text = "HerstellerNr"
			Me.Panel1.Controls.Add( Me.HerstellerNrLabel )
			'
			' HerstellerNrTextBox
			'
			Me.HerstellerNrTextBox = New System.Windows.Forms.TextBox()
			Me.HerstellerNrTextBox.DataBindings.Add(New System.Windows.Forms.Binding("Text", Me.grartikelBindingSource, "HerstellerNr", true ))
			Me.HerstellerNrTextBox.Location = New System.Drawing.Point( 488, 128 )
			Me.HerstellerNrTextBox.Name = "HerstellerNrTextBox"
			Me.HerstellerNrTextBox.Size = New System.Drawing.Size( 100, 20 )
			Me.HerstellerNrTextBox.TabIndex = 42
			AddHandler Me.HerstellerNrTextBox.Validating, AddressOf Me.HerstellerNrTextBox_Validating
			Me.Panel1.Controls.Add( Me.HerstellerNrTextBox)
			'
			' ProduktAktivLabel
			'
			Me.ProduktAktivLabel = New System.Windows.Forms.Label()
			Me.ProduktAktivLabel.AutoSize = True
			Me.ProduktAktivLabel.Location = New System.Drawing.Point( 410, 154 )
			Me.ProduktAktivLabel.Name = "ProduktAktivLabel"
			Me.ProduktAktivLabel.Size = New System.Drawing.Size( 68, 13 )
			Me.ProduktAktivLabel.TabIndex = 43
			Me.ProduktAktivLabel.Text = "ProduktAktiv"
			Me.Panel1.Controls.Add( Me.ProduktAktivLabel )
			'
			'ProduktAktivCheckBox
			'
			Me.ProduktAktivCheckBox = New System.Windows.Forms.CheckBox()
			Me.ProduktAktivCheckBox.AutoSize = True
			Me.ProduktAktivCheckBox.Location = New System.Drawing.Point(488, 157)
			Me.ProduktAktivCheckBox.Name = "ProduktAktivCheckBox"
			Me.ProduktAktivCheckBox.Size = New System.Drawing.Size(15, 14)
			Me.ProduktAktivCheckBox.TabIndex = 44
			Me.ProduktAktivCheckBox.UseVisualStyleBackColor = True
			Me.Panel1.Controls.Add( Me.ProduktAktivCheckBox )
			Me.ProduktAktivCheckBox.DataBindings.Add(New System.Windows.Forms.Binding("Checked", Me.grartikelBindingSource, "ProduktAktiv", True))
			'
			' ShopURLLabel
			'
			Me.ShopURLLabel = New System.Windows.Forms.Label()
			Me.ShopURLLabel.AutoSize = True
			Me.ShopURLLabel.Location = New System.Drawing.Point( 424, 180 )
			Me.ShopURLLabel.Name = "ShopURLLabel"
			Me.ShopURLLabel.Size = New System.Drawing.Size( 54, 13 )
			Me.ShopURLLabel.TabIndex = 45
			Me.ShopURLLabel.Text = "ShopURL"
			Me.Panel1.Controls.Add( Me.ShopURLLabel )
			'
			' ShopURLTextBox
			'
			Me.ShopURLTextBox = New System.Windows.Forms.TextBox()
			Me.ShopURLTextBox.DataBindings.Add(New System.Windows.Forms.Binding("Text", Me.grartikelBindingSource, "ShopURL", true ))
			Me.ShopURLTextBox.Location = New System.Drawing.Point( 488, 180 )
			Me.ShopURLTextBox.Name = "ShopURLTextBox"
			Me.ShopURLTextBox.Size = New System.Drawing.Size( 100, 20 )
			Me.ShopURLTextBox.TabIndex = 46
			AddHandler Me.ShopURLTextBox.Validating, AddressOf Me.ShopURLTextBox_Validating
			Me.Panel1.Controls.Add( Me.ShopURLTextBox)
			'
			' HerstellerURLLabel
			'
			Me.HerstellerURLLabel = New System.Windows.Forms.Label()
			Me.HerstellerURLLabel.AutoSize = True
			Me.HerstellerURLLabel.Location = New System.Drawing.Point( 405, 206 )
			Me.HerstellerURLLabel.Name = "HerstellerURLLabel"
			Me.HerstellerURLLabel.Size = New System.Drawing.Size( 73, 13 )
			Me.HerstellerURLLabel.TabIndex = 47
			Me.HerstellerURLLabel.Text = "HerstellerURL"
			Me.Panel1.Controls.Add( Me.HerstellerURLLabel )
			'
			' HerstellerURLTextBox
			'
			Me.HerstellerURLTextBox = New System.Windows.Forms.TextBox()
			Me.HerstellerURLTextBox.DataBindings.Add(New System.Windows.Forms.Binding("Text", Me.grartikelBindingSource, "HerstellerURL", true ))
			Me.HerstellerURLTextBox.Location = New System.Drawing.Point( 488, 206 )
			Me.HerstellerURLTextBox.Name = "HerstellerURLTextBox"
			Me.HerstellerURLTextBox.Size = New System.Drawing.Size( 100, 20 )
			Me.HerstellerURLTextBox.TabIndex = 48
			AddHandler Me.HerstellerURLTextBox.Validating, AddressOf Me.HerstellerURLTextBox_Validating
			Me.Panel1.Controls.Add( Me.HerstellerURLTextBox)
			'
			' ModifikationenLabel
			'
			Me.ModifikationenLabel = New System.Windows.Forms.Label()
			Me.ModifikationenLabel.AutoSize = True
			Me.ModifikationenLabel.Location = New System.Drawing.Point( 402, 232 )
			Me.ModifikationenLabel.Name = "ModifikationenLabel"
			Me.ModifikationenLabel.Size = New System.Drawing.Size( 76, 13 )
			Me.ModifikationenLabel.TabIndex = 49
			Me.ModifikationenLabel.Text = "Modifikationen"
			Me.Panel1.Controls.Add( Me.ModifikationenLabel )
			'
			' ModifikationenTextBox
			'
			Me.ModifikationenTextBox = New System.Windows.Forms.TextBox()
			Me.ModifikationenTextBox.DataBindings.Add(New System.Windows.Forms.Binding("Text", Me.grartikelBindingSource, "Modifikationen", true ))
			Me.ModifikationenTextBox.Location = New System.Drawing.Point( 488, 232 )
			Me.ModifikationenTextBox.Name = "ModifikationenTextBox"
			Me.ModifikationenTextBox.Size = New System.Drawing.Size( 100, 20 )
			Me.ModifikationenTextBox.TabIndex = 50
			AddHandler Me.ModifikationenTextBox.Validating, AddressOf Me.ModifikationenTextBox_Validating
			Me.Panel1.Controls.Add( Me.ModifikationenTextBox)
			'
			' HerstellerRabattLabel
			'
			Me.HerstellerRabattLabel = New System.Windows.Forms.Label()
			Me.HerstellerRabattLabel.AutoSize = True
			Me.HerstellerRabattLabel.Location = New System.Drawing.Point( 395, 258 )
			Me.HerstellerRabattLabel.Name = "HerstellerRabattLabel"
			Me.HerstellerRabattLabel.Size = New System.Drawing.Size( 83, 13 )
			Me.HerstellerRabattLabel.TabIndex = 51
			Me.HerstellerRabattLabel.Text = "HerstellerRabatt"
			Me.Panel1.Controls.Add( Me.HerstellerRabattLabel )
			'
			' HerstellerRabattTextBox
			'
			Me.HerstellerRabattTextBox = New System.Windows.Forms.TextBox()
			Me.HerstellerRabattTextBox.DataBindings.Add(New System.Windows.Forms.Binding("Text", Me.grartikelBindingSource, "HerstellerRabatt", true ))
			Me.HerstellerRabattTextBox.Location = New System.Drawing.Point( 488, 258 )
			Me.HerstellerRabattTextBox.Name = "HerstellerRabattTextBox"
			Me.HerstellerRabattTextBox.Size = New System.Drawing.Size( 100, 20 )
			Me.HerstellerRabattTextBox.TabIndex = 52
			AddHandler Me.HerstellerRabattTextBox.Validating, AddressOf Me.HerstellerRabattTextBox_Validating
			Me.Panel1.Controls.Add( Me.HerstellerRabattTextBox)
			'
			' HerstellerRabattTextLabel
			'
			Me.HerstellerRabattTextLabel = New System.Windows.Forms.Label()
			Me.HerstellerRabattTextLabel.AutoSize = True
			Me.HerstellerRabattTextLabel.Location = New System.Drawing.Point( 374, 284 )
			Me.HerstellerRabattTextLabel.Name = "HerstellerRabattTextLabel"
			Me.HerstellerRabattTextLabel.Size = New System.Drawing.Size( 104, 13 )
			Me.HerstellerRabattTextLabel.TabIndex = 53
			Me.HerstellerRabattTextLabel.Text = "HerstellerRabattText"
			Me.Panel1.Controls.Add( Me.HerstellerRabattTextLabel )
			'
			' HerstellerRabattTextTextBox
			'
			Me.HerstellerRabattTextTextBox = New System.Windows.Forms.TextBox()
			Me.HerstellerRabattTextTextBox.DataBindings.Add(New System.Windows.Forms.Binding("Text", Me.grartikelBindingSource, "HerstellerRabattText", true ))
			Me.HerstellerRabattTextTextBox.Location = New System.Drawing.Point( 488, 284 )
			Me.HerstellerRabattTextTextBox.Name = "HerstellerRabattTextTextBox"
			Me.HerstellerRabattTextTextBox.Size = New System.Drawing.Size( 100, 20 )
			Me.HerstellerRabattTextTextBox.TabIndex = 54
			AddHandler Me.HerstellerRabattTextTextBox.Validating, AddressOf Me.HerstellerRabattTextTextBox_Validating
			Me.Panel1.Controls.Add( Me.HerstellerRabattTextTextBox)
			'
			' AngelegtAnLabel
			'
			Me.AngelegtAnLabel = New System.Windows.Forms.Label()
			Me.AngelegtAnLabel.AutoSize = True
			Me.AngelegtAnLabel.Location = New System.Drawing.Point( 416, 310 )
			Me.AngelegtAnLabel.Name = "AngelegtAnLabel"
			Me.AngelegtAnLabel.Size = New System.Drawing.Size( 62, 13 )
			Me.AngelegtAnLabel.TabIndex = 55
			Me.AngelegtAnLabel.Text = "AngelegtAn"
			Me.Panel1.Controls.Add( Me.AngelegtAnLabel )
			'
			'AngelegtAn_dateTimePicker
			'
			Me.AngelegtAn_dateTimePicker = New System.Windows.Forms.DateTimePicker()
			Me.AngelegtAn_dateTimePicker.CustomFormat = "dd/MM/yyyy, hh:mm" 
			Me.AngelegtAn_dateTimePicker.Format = System.Windows.Forms.DateTimePickerFormat.Custom
			Me.AngelegtAn_dateTimePicker.Location = New System.Drawing.Point(488, 310)
			Me.AngelegtAn_dateTimePicker.Name = "AngelegtAn_dateTimePicker"
			Me.AngelegtAn_dateTimePicker.Size = New System.Drawing.Size(200, 20)
			Me.AngelegtAn_dateTimePicker.TabIndex = 56
			Me.AngelegtAn_dateTimePicker.Value = New System.DateTime(2014, 5, 26, 17, 35, 11, 0)
			Me.AngelegtAn_dateTimePicker.DataBindings.Add(New System.Windows.Forms.Binding("Text", Me.grartikelBindingSource, "AngelegtAn", True ))
			Me.Panel1.Controls.Add( Me.AngelegtAn_dateTimePicker )
			'
			' BruttoGewichtLabel
			'
			Me.BruttoGewichtLabel = New System.Windows.Forms.Label()
			Me.BruttoGewichtLabel.AutoSize = True
			Me.BruttoGewichtLabel.Location = New System.Drawing.Point( 404, 336 )
			Me.BruttoGewichtLabel.Name = "BruttoGewichtLabel"
			Me.BruttoGewichtLabel.Size = New System.Drawing.Size( 74, 13 )
			Me.BruttoGewichtLabel.TabIndex = 57
			Me.BruttoGewichtLabel.Text = "BruttoGewicht"
			Me.Panel1.Controls.Add( Me.BruttoGewichtLabel )
			'
			' BruttoGewichtTextBox
			'
			Me.BruttoGewichtTextBox = New System.Windows.Forms.TextBox()
			Me.BruttoGewichtTextBox.DataBindings.Add(New System.Windows.Forms.Binding("Text", Me.grartikelBindingSource, "BruttoGewicht", true ))
			Me.BruttoGewichtTextBox.Location = New System.Drawing.Point( 488, 336 )
			Me.BruttoGewichtTextBox.Name = "BruttoGewichtTextBox"
			Me.BruttoGewichtTextBox.Size = New System.Drawing.Size( 100, 20 )
			Me.BruttoGewichtTextBox.TabIndex = 58
			AddHandler Me.BruttoGewichtTextBox.Validating, AddressOf Me.BruttoGewichtTextBox_Validating
			Me.Panel1.Controls.Add( Me.BruttoGewichtTextBox)
			'
			' NettoGewichtLabel
			'
			Me.NettoGewichtLabel = New System.Windows.Forms.Label()
			Me.NettoGewichtLabel.AutoSize = True
			Me.NettoGewichtLabel.Location = New System.Drawing.Point( 406, 362 )
			Me.NettoGewichtLabel.Name = "NettoGewichtLabel"
			Me.NettoGewichtLabel.Size = New System.Drawing.Size( 72, 13 )
			Me.NettoGewichtLabel.TabIndex = 59
			Me.NettoGewichtLabel.Text = "NettoGewicht"
			Me.Panel1.Controls.Add( Me.NettoGewichtLabel )
			'
			' NettoGewichtTextBox
			'
			Me.NettoGewichtTextBox = New System.Windows.Forms.TextBox()
			Me.NettoGewichtTextBox.DataBindings.Add(New System.Windows.Forms.Binding("Text", Me.grartikelBindingSource, "NettoGewicht", true ))
			Me.NettoGewichtTextBox.Location = New System.Drawing.Point( 488, 362 )
			Me.NettoGewichtTextBox.Name = "NettoGewichtTextBox"
			Me.NettoGewichtTextBox.Size = New System.Drawing.Size( 100, 20 )
			Me.NettoGewichtTextBox.TabIndex = 60
			AddHandler Me.NettoGewichtTextBox.Validating, AddressOf Me.NettoGewichtTextBox_Validating
			Me.Panel1.Controls.Add( Me.NettoGewichtTextBox)
			'
			' TaraGewichtLabel
			'
			Me.TaraGewichtLabel = New System.Windows.Forms.Label()
			Me.TaraGewichtLabel.AutoSize = True
			Me.TaraGewichtLabel.Location = New System.Drawing.Point( 410, 388 )
			Me.TaraGewichtLabel.Name = "TaraGewichtLabel"
			Me.TaraGewichtLabel.Size = New System.Drawing.Size( 68, 13 )
			Me.TaraGewichtLabel.TabIndex = 61
			Me.TaraGewichtLabel.Text = "TaraGewicht"
			Me.Panel1.Controls.Add( Me.TaraGewichtLabel )
			'
			' TaraGewichtTextBox
			'
			Me.TaraGewichtTextBox = New System.Windows.Forms.TextBox()
			Me.TaraGewichtTextBox.DataBindings.Add(New System.Windows.Forms.Binding("Text", Me.grartikelBindingSource, "TaraGewicht", true ))
			Me.TaraGewichtTextBox.Location = New System.Drawing.Point( 488, 388 )
			Me.TaraGewichtTextBox.Name = "TaraGewichtTextBox"
			Me.TaraGewichtTextBox.Size = New System.Drawing.Size( 100, 20 )
			Me.TaraGewichtTextBox.TabIndex = 62
			AddHandler Me.TaraGewichtTextBox.Validating, AddressOf Me.TaraGewichtTextBox_Validating
			Me.Panel1.Controls.Add( Me.TaraGewichtTextBox)
			'
			' AngelegtAmLabel
			'
			Me.AngelegtAmLabel = New System.Windows.Forms.Label()
			Me.AngelegtAmLabel.AutoSize = True
			Me.AngelegtAmLabel.Location = New System.Drawing.Point( 414, 414 )
			Me.AngelegtAmLabel.Name = "AngelegtAmLabel"
			Me.AngelegtAmLabel.Size = New System.Drawing.Size( 64, 13 )
			Me.AngelegtAmLabel.TabIndex = 63
			Me.AngelegtAmLabel.Text = "AngelegtAm"
			Me.Panel1.Controls.Add( Me.AngelegtAmLabel )
			'
			'AngelegtAm_dateTimePicker
			'
			Me.AngelegtAm_dateTimePicker = New System.Windows.Forms.DateTimePicker()
			Me.AngelegtAm_dateTimePicker.CustomFormat = "dd/MM/yyyy, hh:mm" 
			Me.AngelegtAm_dateTimePicker.Format = System.Windows.Forms.DateTimePickerFormat.Custom
			Me.AngelegtAm_dateTimePicker.Location = New System.Drawing.Point(488, 414)
			Me.AngelegtAm_dateTimePicker.Name = "AngelegtAm_dateTimePicker"
			Me.AngelegtAm_dateTimePicker.Size = New System.Drawing.Size(200, 20)
			Me.AngelegtAm_dateTimePicker.TabIndex = 64
			Me.AngelegtAm_dateTimePicker.Value = New System.DateTime(2014, 5, 26, 17, 35, 11, 0)
			Me.AngelegtAm_dateTimePicker.DataBindings.Add(New System.Windows.Forms.Binding("Text", Me.grartikelBindingSource, "AngelegtAm", True ))
			Me.Panel1.Controls.Add( Me.AngelegtAm_dateTimePicker )
			'
			' NichtBestellbarLabel
			'
			Me.NichtBestellbarLabel = New System.Windows.Forms.Label()
			Me.NichtBestellbarLabel.AutoSize = True
			Me.NichtBestellbarLabel.Location = New System.Drawing.Point( 400, 440 )
			Me.NichtBestellbarLabel.Name = "NichtBestellbarLabel"
			Me.NichtBestellbarLabel.Size = New System.Drawing.Size( 78, 13 )
			Me.NichtBestellbarLabel.TabIndex = 65
			Me.NichtBestellbarLabel.Text = "NichtBestellbar"
			Me.Panel1.Controls.Add( Me.NichtBestellbarLabel )
			'
			'NichtBestellbarCheckBox
			'
			Me.NichtBestellbarCheckBox = New System.Windows.Forms.CheckBox()
			Me.NichtBestellbarCheckBox.AutoSize = True
			Me.NichtBestellbarCheckBox.Location = New System.Drawing.Point(488, 443)
			Me.NichtBestellbarCheckBox.Name = "NichtBestellbarCheckBox"
			Me.NichtBestellbarCheckBox.Size = New System.Drawing.Size(15, 14)
			Me.NichtBestellbarCheckBox.TabIndex = 66
			Me.NichtBestellbarCheckBox.UseVisualStyleBackColor = True
			Me.Panel1.Controls.Add( Me.NichtBestellbarCheckBox )
			Me.NichtBestellbarCheckBox.DataBindings.Add(New System.Windows.Forms.Binding("Checked", Me.grartikelBindingSource, "NichtBestellbar", True))
			'
			' ProduktAktivOnlineLabel
			'
			Me.ProduktAktivOnlineLabel = New System.Windows.Forms.Label()
			Me.ProduktAktivOnlineLabel.AutoSize = True
			Me.ProduktAktivOnlineLabel.Location = New System.Drawing.Point( 380, 466 )
			Me.ProduktAktivOnlineLabel.Name = "ProduktAktivOnlineLabel"
			Me.ProduktAktivOnlineLabel.Size = New System.Drawing.Size( 98, 13 )
			Me.ProduktAktivOnlineLabel.TabIndex = 67
			Me.ProduktAktivOnlineLabel.Text = "ProduktAktivOnline"
			Me.Panel1.Controls.Add( Me.ProduktAktivOnlineLabel )
			'
			' ProduktAktivOnlineTextBox
			'
			Me.ProduktAktivOnlineTextBox = New System.Windows.Forms.TextBox()
			Me.ProduktAktivOnlineTextBox.DataBindings.Add(New System.Windows.Forms.Binding("Text", Me.grartikelBindingSource, "ProduktAktivOnline", true ))
			Me.ProduktAktivOnlineTextBox.Location = New System.Drawing.Point( 488, 466 )
			Me.ProduktAktivOnlineTextBox.Name = "ProduktAktivOnlineTextBox"
			Me.ProduktAktivOnlineTextBox.Size = New System.Drawing.Size( 100, 20 )
			Me.ProduktAktivOnlineTextBox.TabIndex = 68
			AddHandler Me.ProduktAktivOnlineTextBox.Validating, AddressOf Me.ProduktAktivOnlineTextBox_Validating
			Me.Panel1.Controls.Add( Me.ProduktAktivOnlineTextBox)
			' 
			' panel4
			' 
			Me.panel4.Dock = System.Windows.Forms.DockStyle.Right
			Me.panel4.Location = New System.Drawing.Point(656, 0)
			Me.panel4.Name = "panel4"
			Me.panel4.Size = New System.Drawing.Size(10, 183)
			Me.panel4.TabIndex = 3
			' 
			' panel3
			' 
			Me.panel3.Controls.Add(Me.Panel1)
			Me.panel3.Controls.Add(Me.panel4)
			Me.panel3.Controls.Add(Me.panel5)
			Me.panel3.Controls.Add(Me.panel6)
			Me.panel3.Dock = System.Windows.Forms.DockStyle.Fill
			Me.panel3.Location = new System.Drawing.Point(0, 25)
			Me.panel3.Name = "panel3"
			Me.panel3.Size = New System.Drawing.Size(666, 183)
			Me.panel3.TabIndex = 19
			' 
			' panel5
			' 
			Me.panel5.Dock = System.Windows.Forms.DockStyle.Left
			Me.panel5.Location = New System.Drawing.Point(0, 0)
			Me.panel5.Name = "panel5"
			Me.panel5.Size = New System.Drawing.Size(10, 183)
			Me.panel5.TabIndex = 5
			' 
			' panel6
			' 
			Me.panel6.Dock = System.Windows.Forms.DockStyle.Bottom
			Me.panel6.Location = New System.Drawing.Point(0, 324)
			Me.panel6.Name = "panel6"
			Me.panel6.Size = New System.Drawing.Size(400, 10)
			Me.panel6.TabIndex = 6
			
			'
			'frmgrartikel
			'
			Me.AutoScaleDimensions = New System.Drawing.SizeF(6.0!, 13.0!)
			Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
			Me.ClientSize = New System.Drawing.Size(400, 359)
			Me.Name = "frmgrartikel"
			Me.Text = "frmgrartikel"
			CType(Me.BindingNavigator1, System.ComponentModel.ISupportInitialize).EndInit()
			Me.BindingNavigator1.ResumeLayout(False)
			Me.BindingNavigator1.PerformLayout()
			CType(Me.ErrorProvider1, System.ComponentModel.ISupportInitialize).EndInit()
			Me.Text = "Grartikel"
			CType(Me.newDataSet, System.ComponentModel.ISupportInitialize).EndInit()
			CType(Me.grartikelBindingSource, System.ComponentModel.ISupportInitialize).EndInit()
			Me.Controls.Add(Me.panel3)
			Me.panel3.ResumeLayout(False)
			Me.panel3.PerformLayout()
			
			Me.Controls.Add(Me.BindingNavigator1)
			Me.Panel1.ResumeLayout(False)
			Me.Panel1.PerformLayout()
			Me.ResumeLayout(False)
			Me.PerformLayout()
			
		End Sub
		Friend WithEvents BindingNavigator1 As System.Windows.Forms.BindingNavigator
		Friend WithEvents BindingNavigatorAddNewItem As System.Windows.Forms.ToolStripButton
		Friend WithEvents BindingNavigatorCountItem As System.Windows.Forms.ToolStripLabel
		Friend WithEvents BindingNavigatorDeleteItem As System.Windows.Forms.ToolStripButton
		Friend WithEvents BindingNavigatorMoveFirstItem As System.Windows.Forms.ToolStripButton
		Friend WithEvents BindingNavigatorMovePreviousItem As System.Windows.Forms.ToolStripButton
		Friend WithEvents BindingNavigatorSeparator As System.Windows.Forms.ToolStripSeparator
		Friend WithEvents BindingNavigatorPositionItem As System.Windows.Forms.ToolStripTextBox
		Friend WithEvents BindingNavigatorSeparator1 As System.Windows.Forms.ToolStripSeparator
		Friend WithEvents BindingNavigatorMoveNextItem As System.Windows.Forms.ToolStripButton
		Friend WithEvents BindingNavigatorMoveLastItem As System.Windows.Forms.ToolStripButton
		Friend WithEvents BindingNavigatorSeparator2 As System.Windows.Forms.ToolStripSeparator
		Friend WithEvents ToolStripButton1 As System.Windows.Forms.ToolStripButton
		Friend WithEvents ErrorProvider1 As System.Windows.Forms.ErrorProvider
		Friend WithEvents Panel1 As System.Windows.Forms.Panel
		Friend WithEvents newDataSet As NewDataSet
		Friend WithEvents grartikelBindingSource As System.Windows.Forms.BindingSource
		Friend WithEvents ArtNrTextBox As System.Windows.Forms.TextBox
		Friend WithEvents ArtNrLabel As System.Windows.Forms.Label
		Friend WithEvents EANTextBox As System.Windows.Forms.TextBox
		Friend WithEvents EANLabel As System.Windows.Forms.Label
		Friend WithEvents BarcodeTextBox As System.Windows.Forms.TextBox
		Friend WithEvents BarcodeLabel As System.Windows.Forms.Label
		Friend WithEvents BezeichnungTextBox As System.Windows.Forms.TextBox
		Friend WithEvents BezeichnungLabel As System.Windows.Forms.Label
		Friend WithEvents Bezeichnung1TextBox As System.Windows.Forms.TextBox
		Friend WithEvents Bezeichnung1Label As System.Windows.Forms.Label
		Friend WithEvents BeschreibungTextBox As System.Windows.Forms.TextBox
		Friend WithEvents BeschreibungLabel As System.Windows.Forms.Label
		Friend WithEvents EinheitTextBox As System.Windows.Forms.TextBox
		Friend WithEvents EinheitLabel As System.Windows.Forms.Label
		Friend WithEvents PreisATSTextBox As System.Windows.Forms.TextBox
		Friend WithEvents PreisATSLabel As System.Windows.Forms.Label
		Friend WithEvents PreisEuroTextBox As System.Windows.Forms.TextBox
		Friend WithEvents PreisEuroLabel As System.Windows.Forms.Label
		Friend WithEvents PreisATS_BruttoTextBox As System.Windows.Forms.TextBox
		Friend WithEvents PreisATS_BruttoLabel As System.Windows.Forms.Label
		Friend WithEvents LagerArtikelCheckBox As System.Windows.Forms.CheckBox
		Friend WithEvents LagerArtikelLabel As System.Windows.Forms.Label
		Friend WithEvents EKPreisTextBox As System.Windows.Forms.TextBox
		Friend WithEvents EKPreisLabel As System.Windows.Forms.Label
		Friend WithEvents LEKPreisTextBox As System.Windows.Forms.TextBox
		Friend WithEvents LEKPreisLabel As System.Windows.Forms.Label
		Friend WithEvents SeriennummerCheckBox As System.Windows.Forms.CheckBox
		Friend WithEvents SeriennummerLabel As System.Windows.Forms.Label
		Friend WithEvents LieferantNRTextBox As System.Windows.Forms.TextBox
		Friend WithEvents LieferantNRLabel As System.Windows.Forms.Label
		Friend WithEvents SetArtikelCheckBox As System.Windows.Forms.CheckBox
		Friend WithEvents SetArtikelLabel As System.Windows.Forms.Label
		Friend WithEvents ArtKatNrTextBox As System.Windows.Forms.TextBox
		Friend WithEvents ArtKatNrLabel As System.Windows.Forms.Label
		Friend WithEvents MWSTTextBox As System.Windows.Forms.TextBox
		Friend WithEvents MWSTLabel As System.Windows.Forms.Label
		Friend WithEvents GewichtTextBox As System.Windows.Forms.TextBox
		Friend WithEvents GewichtLabel As System.Windows.Forms.Label
		Friend WithEvents PictureTextBox As System.Windows.Forms.TextBox
		Friend WithEvents PictureLabel As System.Windows.Forms.Label
		Friend WithEvents HerstellerNrTextBox As System.Windows.Forms.TextBox
		Friend WithEvents HerstellerNrLabel As System.Windows.Forms.Label
		Friend WithEvents ProduktAktivCheckBox As System.Windows.Forms.CheckBox
		Friend WithEvents ProduktAktivLabel As System.Windows.Forms.Label
		Friend WithEvents ShopURLTextBox As System.Windows.Forms.TextBox
		Friend WithEvents ShopURLLabel As System.Windows.Forms.Label
		Friend WithEvents HerstellerURLTextBox As System.Windows.Forms.TextBox
		Friend WithEvents HerstellerURLLabel As System.Windows.Forms.Label
		Friend WithEvents ModifikationenTextBox As System.Windows.Forms.TextBox
		Friend WithEvents ModifikationenLabel As System.Windows.Forms.Label
		Friend WithEvents HerstellerRabattTextBox As System.Windows.Forms.TextBox
		Friend WithEvents HerstellerRabattLabel As System.Windows.Forms.Label
		Friend WithEvents HerstellerRabattTextTextBox As System.Windows.Forms.TextBox
		Friend WithEvents HerstellerRabattTextLabel As System.Windows.Forms.Label
		Friend WithEvents AngelegtAn_dateTimePicker As System.Windows.Forms.DateTimePicker
		Friend WithEvents AngelegtAnLabel As System.Windows.Forms.Label
		Friend WithEvents BruttoGewichtTextBox As System.Windows.Forms.TextBox
		Friend WithEvents BruttoGewichtLabel As System.Windows.Forms.Label
		Friend WithEvents NettoGewichtTextBox As System.Windows.Forms.TextBox
		Friend WithEvents NettoGewichtLabel As System.Windows.Forms.Label
		Friend WithEvents TaraGewichtTextBox As System.Windows.Forms.TextBox
		Friend WithEvents TaraGewichtLabel As System.Windows.Forms.Label
		Friend WithEvents AngelegtAm_dateTimePicker As System.Windows.Forms.DateTimePicker
		Friend WithEvents AngelegtAmLabel As System.Windows.Forms.Label
		Friend WithEvents NichtBestellbarCheckBox As System.Windows.Forms.CheckBox
		Friend WithEvents NichtBestellbarLabel As System.Windows.Forms.Label
		Friend WithEvents ProduktAktivOnlineTextBox As System.Windows.Forms.TextBox
		Friend WithEvents ProduktAktivOnlineLabel As System.Windows.Forms.Label
		Friend WithEvents panel3 As System.Windows.Forms.Panel
		Friend WithEvents panel4 As System.Windows.Forms.Panel
		Friend WithEvents panel5 As System.Windows.Forms.Panel
		Friend WithEvents panel6 As System.Windows.Forms.Panel
		
	End Class
	
End Namespace
