<%@ LANGUAGE = VBScript.Encode%>
<%'@ LANGUAGE = VBScript.Encode  TRANSACTION = Required %>
<%'OPTION explicit%>
<!--#include file="../client/intrasoft/connOpen.aspx"-->
<!--#include file="login.aspx"-->
<!--#include file="../client/intrasoft/functions.aspx"-->
<!--#include file="../client/intrasoft/functionsDictionary.aspx"-->
<!--#include file="../client/intrasoft/functionsGUI.aspx"-->
<!--#include file="../client/intrasoft/functionsIntraSell.aspx"-->
<!--#include file="../client/functionsMerchants.aspx"-->